import { useState } from "react";
import { trpc, errorMessage } from "../lib/trpc.ts";
import { useCan } from "../lib/auth.tsx";
import { Link, navigate } from "../lib/router.tsx";
import { PageHead, Card, Table, Badge, Button, Loading, ErrorBox, Tabs, KV, Field, Input, Textarea, Select, Checkbox, ActionDialog, Modal, Json, Callout, useToast } from "../ui/kit.tsx";
import { fmtDate, fmtDay, titleCase } from "../lib/format.ts";

export function CampaignsPage() {
  const q = trpc.campaigns.list.useQuery(); const can = useCan(); const [create, setCreate] = useState(false); const toast = useToast();
  const mk = trpc.campaigns.create.useMutation({ onSuccess: () => q.refetch() }); const [f, setF] = useState({ code: "", name: "", startsAt: "", endsAt: "" });
  if (q.isLoading) return <Loading />; if (q.error) return <ErrorBox error={q.error} />;
  return <>
    <PageHead title="Campaigns" sub="Versioned rules and content; activation is gated by the validator." actions={can("campaign.write") && <Button variant="primary" onClick={() => setCreate(true)}>New campaign</Button>} />
    <Card flush><Table rows={q.data ?? []} keyOf={(c) => c.id} onRow={(c) => navigate(`/campaigns/${c.id}`)} cols={[{ h: "Code", c: (c) => <><span className="mono strong">{c.code}</span>{c.sample && <> <Badge tone="warning">sample</Badge></>}</> }, { h: "Name", c: (c) => c.name }, { h: "Status", c: (c) => <Badge status={c.status} /> }, { h: "Window", c: (c) => `${fmtDay(c.startsAt)} – ${fmtDay(c.endsAt)}` }, { h: "Active version", c: (c) => c.activeVersionNo ?? "none" }, { h: "Open decisions", c: (c) => c.openDecisions ? <Badge tone="warning">{c.openDecisions}</Badge> : "0" }, { h: "Controls", c: (c) => [c.controls.pauseIntake && "intake paused", c.controls.pauseOutbound && "outbound paused", c.controls.pauseDraws && "draws paused", c.controls.pauseAutoQualify && "auto-qualify paused"].filter(Boolean).join(", ") || "normal" }]} /></Card>
    {create && <Modal title="New campaign" onClose={() => setCreate(false)} foot={<><Button onClick={() => setCreate(false)}>Cancel</Button><Button variant="primary" loading={mk.isPending} disabled={!f.code || !f.name || !f.startsAt || !f.endsAt} onClick={async () => { try { const c = await mk.mutateAsync({ code: f.code, name: f.name, startsAt: new Date(f.startsAt).toISOString(), endsAt: new Date(f.endsAt).toISOString() }); setCreate(false); navigate(`/campaigns/${c.campaign.id}`); } catch (e) { toast.push(errorMessage(e), "error"); } }}>Create draft</Button></>}>
      <div className="tt-col"><Field label="Code" help="Stable identifier, e.g. BRAND-SUGAR-2026"><Input value={f.code} onChange={(e) => setF({ ...f, code: e.target.value.toUpperCase() })} /></Field><Field label="Name"><Input value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} /></Field><div className="form-row"><Field label="Starts"><Input type="datetime-local" value={f.startsAt} onChange={(e) => setF({ ...f, startsAt: e.target.value })} /></Field><Field label="Ends"><Input type="datetime-local" value={f.endsAt} onChange={(e) => setF({ ...f, endsAt: e.target.value })} /></Field></div><p className="small muted">Rules, content, prize plan and periods are added as a version on the next screen. A draft campaign is invisible to participants.</p></div>
    </Modal>}
  </>;
}

type Tab = "overview" | "versions" | "periods" | "outlets" | "decisions" | "activation";
export function CampaignDetailPage({ id }: { id: string }) {
  const q = trpc.campaigns.get.useQuery({ campaignId: id }); const can = useCan(); const toast = useToast(); const [tab, setTab] = useState<Tab>("overview"); const utils = trpc.useUtils();
  const refresh = () => utils.campaigns.get.invalidate({ campaignId: id });
  const setStatus = trpc.campaigns.setStatus.useMutation({ onSuccess: refresh }); const setControls = trpc.campaigns.setControls.useMutation({ onSuccess: refresh }); const clone = trpc.campaigns.clone.useMutation();
  const [dialog, setDialog] = useState<null | "status" | "clone">(null);
  if (q.isLoading) return <Loading />; if (q.error) return <ErrorBox error={q.error} />; const d = q.data!; const c = d.campaign;
  const next: Record<string, string[]> = { draft: ["active"], active: ["paused", "closed"], paused: ["active", "closed"], closed: ["archived"], archived: [] };
  return <>
    <PageHead title={<>{c.name} <Badge status={c.status} /></>} sub={<><span className="mono">{c.code}</span> · {fmtDay(c.startsAt)} – {fmtDay(c.endsAt)} · {c.timezone}{c.sample ? " · sample configuration" : ""}</>} actions={<>{can("campaign.activate") && next[c.status]?.length > 0 && <Button variant="primary" onClick={() => setDialog("status")}>Change status</Button>}{can("campaign.write") && <Button onClick={() => setDialog("clone")}>Clone</Button>}</>} />
    <Tabs tabs={[{ id: "overview", label: "Overview & controls" }, { id: "versions", label: `Versions (${d.versions.length})` }, { id: "periods", label: `Periods (${d.periods.length})` }, { id: "outlets", label: `Outlets (${d.outletCount})` }, { id: "decisions", label: "Client decisions" }, { id: "activation", label: "Activation check" }]} value={tab} onChange={setTab} />
    {tab === "overview" && <div className="tt-grid c2">
      <Card title="Summary"><KV rows={[["Status", <Badge status={c.status} />], ["Active version", d.activeVersion ? `v${d.activeVersion.versionNo} · ${d.activeVersion.configHash.slice(0, 12)}…` : "none (participants see a closed promotion)"], ["Periods", d.periods.map((p) => `${p.code} (${p.status})`).join(", ") || "–"], ["Outlets", d.outletCount], ["Created", fmtDate(c.createdAt)]]} /></Card>
      <Card title="Operational controls"><p className="small muted">Immediate, reversible switches. Each change is audited.</p><div className="tt-col">{([["pauseIntake", "Pause intake (participants are told entries are paused)"], ["pauseAutoQualify", "Pause automatic qualification (everything goes to review)"], ["pauseOutbound", "Pause outbound messages (they queue)"], ["pauseDraws", "Pause draws (freeze is refused)"]] as const).map(([k, label]) => <Checkbox key={k} label={label} checked={d.controls[k]} disabled={!can("campaign.write")} onChange={async (e) => { try { await setControls.mutateAsync({ campaignId: id, [k]: e.target.checked }); } catch (e2) { toast.push(errorMessage(e2), "error"); } }} />)}</div></Card>
    </div>}
    {tab === "versions" && <VersionsTab campaignId={id} versions={d.versions} activeId={d.activeVersion?.id ?? null} onChange={refresh} />}
    {tab === "periods" && <PeriodsTab campaignId={id} periods={d.periods} onChange={refresh} />}
    {tab === "outlets" && <OutletsTab campaignId={id} onChange={refresh} />}
    {tab === "decisions" && <DecisionsTab campaignId={id} decisions={d.decisions} onChange={refresh} />}
    {tab === "activation" && <ActivationTab campaignId={id} />}
    {dialog === "status" && <ActionDialog title="Change campaign status" description={`Current status: ${c.status}. A production activation runs the validator first.`} fields={[{ key: "status", label: "New status", type: "select", required: true, options: next[c.status].map((s) => ({ value: s, label: titleCase(s) })) }, { key: "reason", label: "Reason", type: "textarea" }]} onConfirm={async (v) => { await setStatus.mutateAsync({ campaignId: id, status: v.status as "active" | "paused" | "closed" | "archived", reason: v.reason || undefined }); toast.push("Status changed", "success"); }} onClose={() => setDialog(null)} />}
    {dialog === "clone" && <ActionDialog title="Clone campaign" description="Copies the active configuration into a new draft campaign with no participants, submissions or draws." fields={[{ key: "code", label: "New code", required: true }, { key: "name", label: "Name" }]} confirmLabel="Clone" onConfirm={async (v) => { const n = await clone.mutateAsync({ campaignId: id, code: v.code.toUpperCase(), name: v.name || undefined }); navigate(`/campaigns/${n.campaign.id}`); }} onClose={() => setDialog(null)} />}
  </>;
}

function VersionsTab({ campaignId, versions, activeId, onChange }: { campaignId: string; versions: Array<{ id: string; versionNo: number; status: string; rules: unknown; content: unknown; flags: unknown; prizePlan: unknown; configHash: string; createdAt: string; activatedAt: string | null }>; activeId: string | null; onChange: () => void }) {
  const can = useCan(); const toast = useToast(); const [sel, setSel] = useState<string | null>(activeId ?? versions.at(-1)?.id ?? null); const v = versions.find((x) => x.id === sel);
  const createV = trpc.campaigns.createVersion.useMutation({ onSuccess: onChange }); const updateV = trpc.campaigns.updateVersion.useMutation({ onSuccess: onChange }); const activate = trpc.campaigns.activateVersion.useMutation({ onSuccess: onChange });
  const [section, setSection] = useState<"rules" | "content" | "flags" | "prizePlan">("rules"); const [draft, setDraft] = useState<string | null>(null); const [confirm, setConfirm] = useState(false);
  const text = draft ?? JSON.stringify(v?.[section] ?? {}, null, 2);
  const save = async () => { try { const parsed = JSON.parse(text); await updateV.mutateAsync({ versionId: v!.id, [section]: parsed }); setDraft(null); toast.push("Draft saved", "success"); } catch (e) { toast.push(errorMessage(e), "error"); } };
  return <div className="tt-grid" style={{ gridTemplateColumns: "280px 1fr" }}>
    <Card title="Versions" actions={can("campaign.write") && <Button size="sm" onClick={async () => { try { const nid = await createV.mutateAsync({ campaignId, fromActive: true }); setSel(nid); setDraft(null); } catch (e) { toast.push(errorMessage(e), "error"); } }}>New draft</Button>}>
      <div className="tt-col" style={{ gap: 6 }}>{versions.map((x) => <button key={x.id} className={`btn ${x.id === sel ? "primary" : ""}`} style={{ justifyContent: "space-between" }} onClick={() => { setSel(x.id); setDraft(null); }}><span>v{x.versionNo}</span><Badge status={x.status} /></button>)}</div>
      <p className="small muted" style={{ marginTop: 12 }}>Activating a version applies prospectively: submissions already decided keep the version they were judged under.</p>
    </Card>
    {v ? <Card title={<h2>v{v.versionNo} <Badge status={v.status} /> <span className="muted small mono">{v.configHash.slice(0, 16)}</span></h2>} actions={<>{v.status === "draft" && can("campaign.write") && <Button variant="primary" size="sm" onClick={() => setConfirm(true)}>Activate</Button>}</>}>
      <Tabs tabs={[{ id: "rules", label: "Rules" }, { id: "content", label: "Content & messages" }, { id: "flags", label: "Flags" }, { id: "prizePlan", label: "Prize plan" }]} value={section} onChange={(s) => { setSection(s); setDraft(null); }} />
      {section === "rules" && <RulesSummary rules={v.rules as Record<string, unknown>} />}
      {section === "content" && <Callout tone="info">Message keys override the defaults per campaign (e.g. <span className="mono">menu</span>, <span className="mono">qualified</span>, <span className="mono">reason.below_minimum</span>). Placeholders such as <span className="mono">{"{reference}"}</span> are kept.</Callout>}
      <Textarea mono value={text} readOnly={v.status !== "draft" || !can("campaign.write")} onChange={(e) => setDraft(e.target.value)} style={{ minHeight: 320, marginTop: 12 }} />
      {v.status === "draft" && can("campaign.write") && <div className="tt-row" style={{ marginTop: 8 }}><Button variant="primary" loading={updateV.isPending} disabled={draft == null} onClick={save}>Save draft</Button><Button variant="ghost" disabled={draft == null} onClick={() => setDraft(null)}>Discard</Button></div>}
      <p className="small muted" style={{ marginTop: 8 }}>Created {fmtDate(v.createdAt)}{v.activatedAt ? ` · activated ${fmtDate(v.activatedAt)}` : ""}</p>
    </Card> : <Card><div className="empty">No versions yet. Create a draft to configure rules, content and prizes.</div></Card>}
    {confirm && v && <ActionDialog title={`Activate v${v.versionNo}`} description="The active version becomes superseded; new conversations and decisions use this configuration from now on." confirmLabel="Activate" onConfirm={async () => { await activate.mutateAsync({ campaignId, versionId: v.id }); toast.push("Version activated", "success"); }} onClose={() => setConfirm(false)} />}
  </div>;
}
function RulesSummary({ rules }: { rules: Record<string, unknown> }) {
  const q = (rules.qualification ?? {}) as Record<string, unknown>; const caps = (rules.caps ?? {}) as Record<string, unknown>; const pw = rules.purchaseWindow as { start?: string; end?: string } | null; const el = (rules.eligibility ?? {}) as Record<string, unknown>; const products = (rules.products ?? []) as Array<{ code: string; name: string; packGrams: number; qualifying?: boolean }>;
  return <KV rows={[["Qualification", `${q.mode === "weight" ? `≥ ${q.minTotalGrams} g total` : `≥ ${q.minPacks} × ${q.packGrams} g packs (≥ ${q.minTotalGrams} g)`}${q.allowMixedPacks ? " · mixed pack sizes count" : ""}`], ["Products", products.map((p) => `${p.name} (${p.packGrams} g${p.qualifying === false ? ", not qualifying" : ""})`).join("; ") || "–"], ["Purchase window", pw ? `${fmtDay(pw.start)} – ${fmtDay(pw.end)}` : "campaign window"], ["Date order", String(rules.dateOrder ?? "DMY")], ["Caps", `${caps.perParticipantPerPeriod ?? "no"} per period · ${caps.perParticipantCampaign ?? "no"} per campaign`], ["Prior winners", String(el.priorWinnerExclusion ?? "none")], ["Min. age", String(el.minAge ?? 18)]]} />;
}
function PeriodsTab({ campaignId, periods, onChange }: { campaignId: string; periods: Array<{ id: string; code: string; label: string; startsAt: string; endsAt: string; drawAt: string | null; status: string; prizePlan: unknown }>; onChange: () => void }) {
  const can = useCan(); const toast = useToast(); const up = trpc.campaigns.upsertPeriod.useMutation({ onSuccess: onChange }); const [edit, setEdit] = useState<null | { code: string; label: string; startsAt: string; endsAt: string; drawAt: string; prizePlan: string }>(null);
  const local = (iso?: string | null) => iso ? new Date(iso).toISOString().slice(0, 16) : "";
  return <Card title="Periods" actions={can("campaign.write") && <Button size="sm" variant="primary" onClick={() => setEdit({ code: "", label: "", startsAt: "", endsAt: "", drawAt: "", prizePlan: "" })}>Add period</Button>}>
    <Table rows={periods} keyOf={(p) => p.id} cols={[{ h: "Code", c: (p) => <span className="mono strong">{p.code}</span> }, { h: "Label", c: (p) => p.label }, { h: "Window (UTC)", c: (p) => `${fmtDate(p.startsAt)} → ${fmtDate(p.endsAt)}` }, { h: "Draw", c: (p) => fmtDate(p.drawAt) }, { h: "Status", c: (p) => <Badge status={p.status} /> }, { h: "Prize plan", c: (p) => p.prizePlan ? "period-specific" : "campaign default" }, { h: "", c: (p) => can("campaign.write") && p.status !== "drawn" ? <Button size="sm" onClick={() => setEdit({ code: p.code, label: p.label, startsAt: local(p.startsAt), endsAt: local(p.endsAt), drawAt: local(p.drawAt), prizePlan: p.prizePlan ? JSON.stringify(p.prizePlan, null, 2) : "" })}>Edit</Button> : null }]} empty="No periods. Draws need at least one." />
    {edit && <Modal title={edit.code ? `Period ${edit.code}` : "New period"} onClose={() => setEdit(null)} foot={<><Button onClick={() => setEdit(null)}>Cancel</Button><Button variant="primary" loading={up.isPending} onClick={async () => { try { await up.mutateAsync({ campaignId, code: edit.code, label: edit.label || undefined, startsAt: new Date(edit.startsAt).toISOString(), endsAt: new Date(edit.endsAt).toISOString(), drawAt: edit.drawAt ? new Date(edit.drawAt).toISOString() : null, prizePlan: edit.prizePlan.trim() ? JSON.parse(edit.prizePlan) : null }); setEdit(null); toast.push("Period saved", "success"); } catch (e) { toast.push(errorMessage(e), "error"); } }}>Save</Button></>}>
      <div className="tt-col"><div className="form-row"><Field label="Code"><Input value={edit.code} onChange={(e) => setEdit({ ...edit, code: e.target.value })} /></Field><Field label="Label"><Input value={edit.label} onChange={(e) => setEdit({ ...edit, label: e.target.value })} /></Field></div><div className="form-row"><Field label="Starts (local)"><Input type="datetime-local" value={edit.startsAt} onChange={(e) => setEdit({ ...edit, startsAt: e.target.value })} /></Field><Field label="Ends (local)"><Input type="datetime-local" value={edit.endsAt} onChange={(e) => setEdit({ ...edit, endsAt: e.target.value })} /></Field><Field label="Draw at"><Input type="datetime-local" value={edit.drawAt} onChange={(e) => setEdit({ ...edit, drawAt: e.target.value })} /></Field></div><Field label="Prize plan override (JSON, optional)"><Textarea mono value={edit.prizePlan} onChange={(e) => setEdit({ ...edit, prizePlan: e.target.value })} placeholder='{"tiers":[{"code":"P1","label":"…","count":2}],"alternatesPerWinner":1,"onePrizePerParticipant":true,"claimDays":7}' /></Field></div>
    </Modal>}
  </Card>;
}
function OutletsTab({ campaignId, onChange }: { campaignId: string; onChange: () => void }) {
  const can = useCan(); const toast = useToast(); const q = trpc.campaigns.outlets.useQuery({ campaignId }); const all = trpc.masterData.outlets.useQuery(); const setOutlets = trpc.campaigns.setOutlets.useMutation({ onSuccess: () => { q.refetch(); onChange(); } }); const imp = trpc.campaigns.importOutlets.useMutation();
  const [csv, setCsv] = useState(""); const [preview, setPreview] = useState<unknown>(null); const [filter, setFilter] = useState("");
  const members = new Map((q.data ?? []).map((o) => [o.id, o.membership]));
  const rows = (all.data ?? []).filter((o) => !filter || `${o.code} ${o.retailer} ${o.branch} ${o.town}`.toLowerCase().includes(filter.toLowerCase()));
  const toggle = async (outletId: string, on: boolean, collection?: boolean) => { const next = (q.data ?? []).filter((o) => o.id !== outletId).map((o) => ({ outletId: o.id, collectionPoint: o.membership.collectionPoint })); if (on) next.push({ outletId, collectionPoint: collection ?? members.get(outletId)?.collectionPoint ?? false }); try { await setOutlets.mutateAsync({ campaignId, members: next }); } catch (e) { toast.push(errorMessage(e), "error"); } };
  return <div className="tt-stack">
    {can("campaign.write") && <Card title="Import outlets from CSV" actions={<a className="btn sm" href="/fixtures/outlets-import-template.csv" download>Template</a>}>
      <p className="small muted">Columns: code, retailer, branch, town, region, aliases (| separated), collection_point (yes/no). Existing codes are updated; new ones created and added to this campaign. Run a dry run first.</p>
      <Textarea mono value={csv} onChange={(e) => setCsv(e.target.value)} placeholder="code,retailer,branch,town,region,aliases,collection_point" />
      <div className="tt-row" style={{ marginTop: 8 }}><input type="file" accept=".csv,text/csv" onChange={async (e) => { const f = e.target.files?.[0]; if (f) setCsv(await f.text()); }} /><Button loading={imp.isPending} disabled={!csv.trim()} onClick={async () => { try { setPreview(await imp.mutateAsync({ campaignId, csv, dryRun: true })); } catch (e) { toast.push(errorMessage(e), "error"); } }}>Dry run</Button><Button variant="primary" loading={imp.isPending} disabled={!csv.trim()} onClick={async () => { try { setPreview(await imp.mutateAsync({ campaignId, csv, dryRun: false })); q.refetch(); all.refetch(); onChange(); toast.push("Import applied", "success"); } catch (e) { toast.push(errorMessage(e), "error"); } }}>Import</Button></div>
      {preview != null && <div style={{ marginTop: 12 }}><Json value={preview} /></div>}
    </Card>}
    <Card title={<h2>Participating outlets <span className="muted">({q.data?.length ?? 0} of {all.data?.length ?? 0})</span></h2>} actions={<Input placeholder="Filter…" value={filter} onChange={(e) => setFilter(e.target.value)} style={{ width: 220 }} />}>
      {q.isLoading || all.isLoading ? <Loading /> : <Table rows={rows} keyOf={(o) => o.id} cols={[{ h: "In campaign", c: (o) => <input type="checkbox" checked={members.has(o.id)} disabled={!can("campaign.write")} onChange={(e) => toggle(o.id, e.target.checked)} /> }, { h: "Code", c: (o) => <span className="mono">{o.code}</span> }, { h: "Retailer", c: (o) => o.retailer }, { h: "Branch", c: (o) => o.branch }, { h: "Town", c: (o) => o.town }, { h: "Region", c: (o) => o.region }, { h: "Collection point", c: (o) => members.has(o.id) ? <input type="checkbox" checked={!!members.get(o.id)?.collectionPoint} disabled={!can("campaign.write")} onChange={(e) => toggle(o.id, true, e.target.checked)} /> : (o.collectionPoint ? "default yes" : "") }, { h: "Active", c: (o) => o.active ? "yes" : <Badge tone="danger">no</Badge> }]} />}
    </Card>
  </div>;
}
function DecisionsTab({ campaignId, decisions, onChange }: { campaignId: string; decisions: Array<{ decisionId: string; question: string; testValue: string | null; approvedValue: string | null; status: string; owner: string | null; evidence: string | null; blocksActivation: boolean; updatedAt: string }>; onChange: () => void }) {
  const can = useCan(); const toast = useToast(); const up = trpc.campaigns.upsertDecision.useMutation({ onSuccess: onChange }); const [edit, setEdit] = useState<typeof decisions[number] | null>(null);
  return <Card title="Client decisions" actions={<span className="small muted">Test values are placeholders; production activation needs every blocking decision approved or marked not required.</span>}>
    <Table rows={decisions} keyOf={(d) => d.decisionId} cols={[{ h: "ID", c: (d) => <span className="mono">{d.decisionId}</span> }, { h: "Question", c: (d) => d.question }, { h: "Test value", c: (d) => <span className="small">{d.testValue}</span> }, { h: "Approved value", c: (d) => d.approvedValue ?? <span className="muted">–</span> }, { h: "Status", c: (d) => <Badge status={d.status} tone={d.status === "approved" || d.status === "not_required" ? "success" : "warning"}>{titleCase(d.status)}</Badge> }, { h: "Blocks", c: (d) => d.blocksActivation ? "yes" : "no" }, { h: "", c: (d) => can("campaign.write") ? <Button size="sm" onClick={() => setEdit(d)}>Update</Button> : null }]} />
    {edit && <Modal title={`${edit.decisionId}: ${edit.question}`} onClose={() => setEdit(null)} foot={<><Button onClick={() => setEdit(null)}>Cancel</Button><Button variant="primary" loading={up.isPending} onClick={async () => { try { await up.mutateAsync({ campaignId, decisionId: edit.decisionId, approvedValue: edit.approvedValue, status: edit.status, owner: edit.owner, evidence: edit.evidence, blocksActivation: edit.blocksActivation }); setEdit(null); toast.push("Decision recorded", "success"); } catch (e) { toast.push(errorMessage(e), "error"); } }}>Save</Button></>}>
      <div className="tt-col"><Field label="Approved value"><Textarea value={edit.approvedValue ?? ""} onChange={(e) => setEdit({ ...edit, approvedValue: e.target.value })} /></Field><div className="form-row"><Field label="Status"><Select value={edit.status} onChange={(e) => setEdit({ ...edit, status: e.target.value })}>{["open", "proposed", "approved", "not_required"].map((s) => <option key={s} value={s}>{titleCase(s)}</option>)}</Select></Field><Field label="Owner"><Input value={edit.owner ?? ""} onChange={(e) => setEdit({ ...edit, owner: e.target.value })} /></Field></div><Field label="Evidence (link or reference to the sign-off)"><Input value={edit.evidence ?? ""} onChange={(e) => setEdit({ ...edit, evidence: e.target.value })} /></Field><Checkbox label="Blocks production activation" checked={edit.blocksActivation} onChange={(e) => setEdit({ ...edit, blocksActivation: e.target.checked })} /></div>
    </Modal>}
  </Card>;
}
function ActivationTab({ campaignId }: { campaignId: string }) {
  const q = trpc.campaigns.activation.useQuery({ campaignId });
  if (q.isLoading) return <Loading />; if (q.error) return <ErrorBox error={q.error} />; const v = q.data!;
  return <Card title={<h2>Production activation validator {v.ok ? <Badge tone="success">pass</Badge> : <Badge tone="danger">{v.failures.filter((f) => f.blocking).length} blocking</Badge>}</h2>} actions={<Button size="sm" onClick={() => q.refetch()}>Re-run</Button>}>
    <p className="small muted">Only a production database can be blocked by this list; in local and test environments it is advisory so that sample configurations stay testable.</p>
    <Table rows={v.failures} keyOf={(f) => f.code} cols={[{ h: "Code", c: (f) => <span className="mono">{f.code}</span> }, { h: "Finding", c: (f) => f.message }, { h: "Blocks", c: (f) => f.blocking ? <Badge tone="danger">yes</Badge> : <Badge>advisory</Badge> }]} empty="Nothing would block activation." />
  </Card>;
}
export { Link };
