import { useState } from "react";
import { trpc, errorMessage, downloadAuth } from "../lib/trpc.ts";
import { Restricted, useCan, useMe } from "../lib/auth.tsx";
import { Link, navigate } from "../lib/router.tsx";
import { PageHead, Card, Table, Badge, Button, Loading, ErrorBox, Select, KV, ActionDialog, Callout, Json, useToast } from "../ui/kit.tsx";
import { fmtDate, titleCase } from "../lib/format.ts";
export function DrawsPage() {
  const campaigns = trpc.campaigns.list.useQuery(); const [cid, setCid] = useState<string>(""); const active = cid || campaigns.data?.find((c) => c.status === "active")?.id || campaigns.data?.[0]?.id || "";
  const camp = trpc.campaigns.get.useQuery({ campaignId: active }, { enabled: !!active }); const draws = trpc.draws.list.useQuery({ campaignId: active }, { enabled: !!active }); const can = useCan(); const toast = useToast();
  const [periodId, setPeriodId] = useState(""); const pid = periodId || camp.data?.periods.find((p) => p.status === "closed")?.id || camp.data?.periods[0]?.id || "";
  const barrier = trpc.draws.barrier.useQuery({ campaignId: active, periodId: pid }, { enabled: !!active && !!pid }); const freeze = trpc.draws.freeze.useMutation(); const [confirm, setConfirm] = useState<null | "freeze" | "override">(null);
  return <>
    <PageHead title="Draws" sub="Barrier → freeze (commit the seed) → execute → independent approval → publish. Every step is audited and re-verifiable." actions={<Select value={active} onChange={(e) => setCid(e.target.value)}>{campaigns.data?.map((c) => <option key={c.id} value={c.id}>{c.code}</option>)}</Select>} />
    <div className="tt-grid c2">
      <Card title="Barrier check" actions={<Select value={pid} onChange={(e) => setPeriodId(e.target.value)}>{camp.data?.periods.map((p) => <option key={p.id} value={p.id}>{p.code} · {p.status}</option>)}</Select>}>
        {barrier.isLoading ? <Loading /> : barrier.error ? <ErrorBox error={barrier.error} /> : barrier.data && <div className="tt-col">
          <KV rows={[["Period", `${barrier.data.period.code} · ${fmtDate(barrier.data.period.startsAt)} → ${fmtDate(barrier.data.period.endsAt)}`], ["Eligible entries", barrier.data.eligible], ["Distinct participants", barrier.data.distinctParticipants], ["Excluded (prior winners)", barrier.data.exclusions], ["Plan", `${barrier.data.plan.totalWinners} winners (${barrier.data.plan.tiers.map((t) => `${t.count}× ${t.code}`).join(", ")}) + ${barrier.data.plan.totalAlternates} alternates${barrier.data.plan.onePrizePerParticipant ? " · one prize per participant" : ""}`]]} />
          {barrier.data.ok ? <Callout tone="success">All checks pass. Freezing takes an immutable snapshot of the candidate list and commits the random seed.</Callout> : <Callout tone="warning"><strong>Blocked:</strong> {barrier.data.blockers.map((b) => <div key={b.code}><span className="mono">{b.code}</span> {b.detail ? <span className="small muted">{JSON.stringify(b.detail)}</span> : null}</div>)}</Callout>}
          {!can("draw.execute") && <Restricted perm="draw.execute" action="Freezing and executing a draw" />}
          {can("draw.execute") && <div className="tt-row"><Button variant="primary" disabled={!barrier.data.ok} onClick={() => setConfirm("freeze")}>Freeze draw</Button>{!barrier.data.ok && barrier.data.blockers.every((b) => b.code === "UNRESOLVED_SUBMISSIONS") && <Button onClick={() => setConfirm("override")}>Freeze anyway (documented override)</Button>}<Button variant="ghost" onClick={() => barrier.refetch()}>Re-check</Button></div>}
        </div>}
      </Card>
      <Card title="Draws in this campaign" flush>{draws.isLoading ? <Loading /> : <Table rows={draws.data ?? []} keyOf={(d) => String(d.id)} onRow={(d) => navigate(`/draws/${d.id}`)} cols={[{ h: "Period", c: (d) => `${d.periodCode} #${d.sequenceNo}` }, { h: "Status", c: (d) => <Badge status={String(d.status)} /> }, { h: "Frozen", c: (d) => fmtDate(String(d.createdAt)) }, { h: "Executed", c: (d) => fmtDate(d.executedAt as string | null) }, { h: "Approved", c: (d) => fmtDate(d.approvedAt as string | null) }, { h: "Published", c: (d) => fmtDate(d.publishedAt as string | null) }]} empty="No draws yet." />}</Card>
    </div>
    {confirm && <ActionDialog title={confirm === "override" ? "Freeze with unresolved submissions" : "Freeze draw"} description={confirm === "override" ? "Submissions still under review will not be in this draw. The override and your reason are recorded in the snapshot and the audit log." : "The candidate list becomes immutable and the seed is committed (its hash is published; the seed itself is revealed only after execution)."} confirmLabel="Freeze" fields={confirm === "override" ? [{ key: "reason", label: "Reason for proceeding", required: true, type: "textarea" }] : []} onConfirm={async (v) => { const d = await freeze.mutateAsync({ campaignId: active, periodId: pid, override: confirm === "override" ? { allow: ["UNRESOLVED_SUBMISSIONS"], reason: v.reason } : null }); toast.push("Draw frozen", "success"); navigate(`/draws/${d.id}`); }} onClose={() => setConfirm(null)} />}
  </>;
}
export function DrawDetailPage({ id }: { id: string }) {
  const q = trpc.draws.get.useQuery({ drawId: id }); const can = useCan(); const { me } = useMe(); const toast = useToast(); const utils = trpc.useUtils(); const refresh = () => utils.draws.get.invalidate({ drawId: id }); const staff = trpc.auth.directory.useQuery();
  const execute = trpc.draws.execute.useMutation({ onSuccess: refresh }); const approve = trpc.draws.approve.useMutation({ onSuccess: refresh }); const reject = trpc.draws.reject.useMutation({ onSuccess: refresh }); const publish = trpc.draws.publish.useMutation({ onSuccess: refresh }); const voidRerun = trpc.draws.voidAndRerun.useMutation();
  const [dialog, setDialog] = useState<null | "execute" | "approve" | "reject" | "publish" | "void">(null);
  if (q.isLoading) return <Loading />; if (q.error) return <ErrorBox error={q.error} />; const d = q.data!; const draw = d.draw as Record<string, unknown>; const status = String(draw.status); const out = draw.output as { winners: Array<{ position: number; entryId: string; participantId: string; prizeCode: string }>; alternates: Array<{ position: number; entryId: string }> } | null; const snap = draw.snapshot as { candidates: unknown[]; exclusions: unknown[]; seedCommitment: string; plan: { totalWinners: number } }; const barrier = draw.barrier as { override?: { reason: string } | null; blockers: Array<{ code: string }> };
  const isOfficer = draw.officerId === me?.id || draw.executedBy === me?.id;
  return <>
    <PageHead title={<>Draw {d.period?.code} #{String(draw.sequenceNo)} <Badge status={status} /></>} sub={<><span className="mono small">{id}</span> · algorithm {String(draw.algorithm)} · <Link to="/draws">All draws</Link>{draw.supersedesId ? <> · re-run of <Link to={`/draws/${draw.supersedesId}`}>{String(draw.supersedesId)}</Link></> : null}</>} actions={<>
      {status === "frozen" && can("draw.execute") && <Button variant="primary" onClick={() => setDialog("execute")}>Execute</Button>}
      {status === "executing" && can("draw.execute") && <Button variant="primary" onClick={() => setDialog("execute")}>Resume execution</Button>}
      {status === "executed" && can("draw.approve") && !isOfficer && <><Button variant="primary" onClick={() => setDialog("approve")}>Approve</Button><Button variant="danger" onClick={() => setDialog("reject")}>Reject</Button></>}
      {status === "executed" && can("draw.approve") && isOfficer && <Callout tone="warning">You froze or executed this draw, so you cannot approve it.</Callout>}
      {["frozen", "executing"].includes(status) && !can("draw.execute") && <Restricted perm="draw.execute" action="Executing this draw" />}
      {status === "executed" && !can("draw.approve") && <Restricted perm="draw.approve" action="Approving or rejecting this draw" />}
      {status === "approved" && !can("winner.manage") && <Restricted perm="winner.manage" action="Publishing the draw and creating winner records" />}
      {status === "approved" && can("winner.manage") && <Button variant="primary" onClick={() => setDialog("publish")}>Publish & create winner records</Button>}
      {["approved", "published"].includes(status) && can("draw.execute") && <Button variant="danger" onClick={() => setDialog("void")}>Void & re-run</Button>}
      {can("draw.bundle") && <Button onClick={async () => { try { await downloadAuth(`/api/draws/${id}/bundle.json`, `draw-${d.period?.code}-${String(draw.sequenceNo)}.json`); } catch (e) { toast.push(errorMessage(e), "error"); } }}>Download audit bundle</Button>}
    </>} />
    {!d.integrity.ok && <Callout tone="danger"><strong>Integrity check failed:</strong> {d.integrity.problems.join("; ")}</Callout>}
    <div className="tt-grid c2" style={{ marginTop: 16 }}>
      <Card title="Evidence"><KV rows={[["Integrity", d.integrity.ok ? <Badge tone="success">recomputed and matches</Badge> : <Badge tone="danger">mismatch</Badge>], ["Candidates", `${d.candidates} eligible · ${(snap.exclusions ?? []).length} excluded`], ["Snapshot hash", <span className="mono small">{String(draw.snapshotHash)}</span>], ["Seed commitment", <span className="mono small">{String(draw.seedCommitment)}</span>], ["Output hash", draw.outputHash ? <span className="mono small">{String(draw.outputHash)}</span> : "not executed"], ["Rules version hash", <span className="mono small">{String(draw.rulesVersionHash ?? "–")}</span>], ["Officer", String(draw.officerId)], ["Executed", draw.executedAt ? `${fmtDate(String(draw.executedAt))} by ${String(draw.executedBy)}` : "–"], ["Approved", draw.approvedAt ? `${fmtDate(String(draw.approvedAt))} by ${String(draw.approverId)}${draw.approvalNote ? ` · ${String(draw.approvalNote)}` : ""}` : "–"], ["Published", draw.publishedAt ? `${fmtDate(String(draw.publishedAt))} by ${String(draw.publishedBy)}` : "–"], ["Voided", draw.voidedAt ? `${fmtDate(String(draw.voidedAt))} by ${String(draw.voidedBy)} (approved by ${String(draw.voidApprovedBy)}) · ${String(draw.voidReason)}` : "–"], ["Barrier override", barrier.override ? <span className="badge warning">{barrier.override.reason}</span> : "none"]]} /></Card>
      <Card title="Execution attempts"><Table rows={d.attempts} keyOf={(a) => a.id} cols={[{ h: "When", c: (a) => fmtDate(a.createdAt) }, { h: "Actor", c: (a) => a.actorId }, { h: "Outcome", c: (a) => <Badge>{a.outcome}</Badge> }, { h: "Detail", c: (a) => a.detail ?? "" }]} empty="Not executed yet." /><p className="small muted" style={{ marginTop: 8 }}>Execution is reserved durably; a crash mid-way resumes and recomputes the same result from the committed seed.</p></Card>
      <Card title={`Result${out ? ` · ${out.winners.length} winners, ${out.alternates.length} alternates` : ""}`}>{out ? <Table rows={[...out.winners.map((w) => ({ ...w, kind: "winner" })), ...out.alternates.map((a) => ({ ...a, kind: "alternate", prizeCode: "–", participantId: "" }))]} keyOf={(w) => `${w.kind}${w.position}`} cols={[{ h: "Kind", c: (w) => <Badge tone={w.kind === "winner" ? "primary" : undefined}>{w.kind}</Badge> }, { h: "#", c: (w) => w.position, num: true }, { h: "Prize", c: (w) => w.prizeCode }, { h: "Entry", c: (w) => <Link to={`/entries/${w.entryId}`}>{w.entryId}</Link> }, { h: "Winner record", c: (w) => { const rec = d.winners.find((x) => x.kind === w.kind && x.position === w.position); return rec ? <Link to={`/winners/${rec.id}`}><Badge status={rec.status} /> {rec.publication === "published" ? <Badge tone="primary">published</Badge> : null}</Link> : <span className="muted">not materialised</span>; } }]} /> : <Callout>Randomness is withheld until execution. The seed commitment above lets anyone verify afterwards that the seed was fixed at freeze time.</Callout>}</Card>
      <Card title="Snapshot"><details><summary className="small muted">Show frozen snapshot ({snap.candidates.length} candidates)</summary><Json value={snap} /></details><details style={{ marginTop: 8 }}><summary className="small muted">Barrier at freeze</summary><Json value={barrier} /></details></Card>
    </div>
    {dialog === "execute" && <ActionDialog title="Execute draw" description="Deterministic sortition from the committed seed. Running it twice yields the same result." confirmLabel="Execute" onConfirm={async () => { await execute.mutateAsync({ drawId: id }); toast.push("Draw executed", "success"); }} onClose={() => setDialog(null)} />}
    {dialog === "approve" && <ActionDialog title="Approve draw" description="Confirms the result you are looking at (the output hash is pinned) after the integrity check is re-run server-side." confirmLabel="Approve" fields={[{ key: "note", label: "Approval note", type: "textarea" }]} onConfirm={async (v) => { await approve.mutateAsync({ drawId: id, expectedOutputHash: String(draw.outputHash), note: v.note || undefined }); toast.push("Draw approved", "success"); }} onClose={() => setDialog(null)} />}
    {dialog === "reject" && <ActionDialog danger title="Reject draw" description="Voids this executed draw; the period stays closed so a new draw can be frozen." confirmLabel="Reject" fields={[{ key: "reason", label: "Reason", required: true, type: "textarea" }]} onConfirm={async (v) => { await reject.mutateAsync({ drawId: id, reason: v.reason }); toast.push("Draw rejected", "success"); }} onClose={() => setDialog(null)} />}
    {dialog === "publish" && <ActionDialog title="Publish draw" description="Marks the draw published and creates winner and alternate records for the claims workflow. Winners are contacted from their own records; public listing is a separate step per winner." confirmLabel="Publish" onConfirm={async () => { const r = await publish.mutateAsync({ drawId: id }); toast.push(`Published · ${r.created} winner records created`, "success"); }} onClose={() => setDialog(null)} />}
    {dialog === "void" && <ActionDialog danger title="Void and re-run" description="Requires a second approver different from you. Uncollected winners are marked replaced and any publication withdrawn; a new draw is frozen with the current eligible list and linked to this one." confirmLabel="Void and freeze re-run" fields={[{ key: "reason", label: "Reason", required: true, type: "textarea" }, { key: "approvedBy", label: "Approving staff member", type: "select", required: true, options: (staff.data ?? []).filter((u) => u.id !== me?.id).map((u) => ({ value: u.id, label: `${u.name} (${u.roles.join(", ")})` })) }]} onConfirm={async (v) => { const n = await voidRerun.mutateAsync({ drawId: id, reason: v.reason, approvedBy: v.approvedBy }); toast.push("Voided; re-run frozen", "success"); navigate(`/draws/${n.id}`); }} onClose={() => setDialog(null)} />}
  </>;
}
export { titleCase };
