import { useState } from "react";
import { trpc } from "../lib/trpc.ts";
import { useCan } from "../lib/auth.tsx";
import { Link, navigate } from "../lib/router.tsx";
import { PageHead, Card, Table, Badge, Button, Loading, ErrorBox, Input, Select, KV, ActionDialog, useToast } from "../ui/kit.tsx";
import { fmtDate, titleCase } from "../lib/format.ts";
export function EntriesPage() {
  const campaigns = trpc.campaigns.list.useQuery(); const [cid, setCid] = useState(""); const [period, setPeriod] = useState(""); const [status, setStatus] = useState(""); const [offset, setOffset] = useState(0);
  const list = trpc.entries.list.useQuery({ campaignId: cid || undefined, period: period || undefined, status: status || undefined, limit: 50, offset });
  return <>
    <PageHead title="Entries" sub="The ledger of awards. Disqualification is an authorised event; the award itself is never deleted." actions={<><Select value={cid} onChange={(e) => { setOffset(0); setCid(e.target.value); }}><option value="">All campaigns</option>{campaigns.data?.map((c) => <option key={c.id} value={c.id}>{c.code}</option>)}</Select><Input placeholder="Period" value={period} onChange={(e) => { setOffset(0); setPeriod(e.target.value); }} style={{ width: 100 }} /><Select value={status} onChange={(e) => { setOffset(0); setStatus(e.target.value); }}><option value="">Any status</option><option value="active">Active</option><option value="excluded">Excluded</option></Select></>} />
    <Card flush>{list.isLoading ? <Loading /> : list.error ? <ErrorBox error={list.error} /> : <Table rows={list.data!.rows} keyOf={(e) => e.id} onRow={(e) => navigate(`/entries/${e.id}`)} cols={[{ h: "Entry", c: (e) => <span className="mono small">{e.id}</span> }, { h: "Submission", c: (e) => <span className="mono">{e.reference}</span> }, { h: "Period", c: (e) => e.periodCode ?? "–" }, { h: "Units", c: (e) => e.units, num: true }, { h: "Status", c: (e) => <Badge status={e.status} /> }, { h: "Awarded by", c: (e) => e.awardedBy }, { h: "Awarded", c: (e) => fmtDate(e.awardedAt) }]} />}
      <div className="tt-row" style={{ padding: 12 }}><Button size="sm" disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 50))}>Previous</Button><Button size="sm" disabled={!list.data?.next} onClick={() => setOffset(list.data!.next!)}>Next</Button></div>
    </Card>
  </>;
}
export function EntryDetailPage({ id }: { id: string }) {
  const q = trpc.entries.get.useQuery({ entryId: id }); const can = useCan(); const toast = useToast(); const utils = trpc.useUtils(); const staff = trpc.auth.directory.useQuery(undefined, { enabled: can("entry.disqualify") });
  const dq = trpc.entries.disqualify.useMutation({ onSuccess: () => utils.entries.get.invalidate({ entryId: id }) }); const ri = trpc.entries.reinstate.useMutation({ onSuccess: () => utils.entries.get.invalidate({ entryId: id }) });
  const [dialog, setDialog] = useState<null | "dq" | "ri">(null);
  if (q.isLoading) return <Loading />; if (q.error) return <ErrorBox error={q.error} />; const d = q.data!; const e = d.entry; const inDraw = d.draws.some((x) => ["frozen", "executing", "executed", "approved", "published"].includes(x.status));
  return <>
    <PageHead title={<>Entry <span className="mono">{e.id}</span> <Badge status={e.status} /></>} sub={<>Period {e.periodCode ?? "none"} · {e.units} unit(s) · awarded {fmtDate(e.awardedAt)} by {e.awardedBy} · <Link to="/entries">All entries</Link></>} actions={<>{can("entry.disqualify") && e.status === "active" && <Button variant="danger" onClick={() => setDialog("dq")}>Disqualify</Button>}{can("entry.disqualify") && e.status === "excluded" && <Button onClick={() => setDialog("ri")}>Reinstate</Button>}</>} />
    <div className="tt-grid c2" style={{ marginTop: 16 }}>
      <Card title="Trace"><KV rows={[["Submission", d.submission ? <Link to={`/submissions/${d.submission.id}`}>{d.submission.reference} · {titleCase(d.submission.status)}</Link> : "–"], ["Participant", <Link to={`/participants/${e.participantId}`}>{e.participantId}</Link>], ["Canonical receipt", d.canonical ? <span className="mono small">{d.canonical.receiptKey} · {d.canonical.status}</span> : "–"], ["Receipt", d.canonical ? `${d.canonical.receiptNo ?? "?"} on ${d.canonical.txnDate ?? "?"}` : "–"], ["Rules version", d.rulesVersion ? `v${d.rulesVersion.versionNo} · ${d.rulesVersion.configHash.slice(0, 12)}…` : "–"], ["Extraction attempts", d.extractions.map((x) => `#${x.attemptNo} ${x.provider} (${x.disposition ?? "–"})`).join("; ")], ["Draws", d.draws.length ? d.draws.map((x) => <div key={x.drawId}><Link to={`/draws/${x.drawId}`}>{x.drawId}</Link> · {x.status} · candidate {x.candidateStatus}</div>) : "not in any draw"]]} /></Card>
      <Card title="Entry events"><Table rows={d.events} keyOf={(x) => x.id} cols={[{ h: "When", c: (x) => fmtDate(x.createdAt) }, { h: "Event", c: (x) => <Badge status={x.type === "disqualified" ? "excluded" : "active"}>{x.type}</Badge> }, { h: "Reason", c: (x) => x.reason }, { h: "Actor", c: (x) => x.actorId }, { h: "Approved by", c: (x) => x.approvedBy ?? "–" }]} empty="No events: the award stands as originally made." /></Card>
      <Card title="Audit trail"><Table rows={d.audit} keyOf={(a) => String(a.id)} cols={[{ h: "When", c: (a) => fmtDate(a.createdAt) }, { h: "Action", c: (a) => <span className="mono">{a.action}</span> }, { h: "Actor", c: (a) => `${a.actorType}:${a.actorId}` }, { h: "Reason", c: (a) => a.reason ?? "" }]} /></Card>
    </div>
    {dialog === "dq" && <ActionDialog danger title="Disqualify entry" description={inDraw ? "This entry is in a frozen or executed draw: an independent approver (different from you) must be named." : "The award record stays; the entry stops counting for draws."} confirmLabel="Disqualify" fields={[{ key: "reason", label: "Reason", required: true }, ...(inDraw ? [{ key: "approvedBy", label: "Approving staff member", type: "select" as const, required: true, options: (staff.data ?? []).map((u) => ({ value: u.id, label: `${u.name} (${u.roles.join(", ")})` })) }] : []), { key: "note", label: "Note", type: "textarea" as const }]} onConfirm={async (v) => { await dq.mutateAsync({ entryId: id, reason: v.reason, approvedBy: v.approvedBy || undefined, note: v.note || undefined }); toast.push("Entry disqualified", "success"); }} onClose={() => setDialog(null)} />}
    {dialog === "ri" && <ActionDialog title="Reinstate entry" fields={[{ key: "reason", label: "Reason", required: true }]} onConfirm={async (v) => { await ri.mutateAsync({ entryId: id, reason: v.reason }); toast.push("Entry reinstated", "success"); }} onClose={() => setDialog(null)} />}
  </>;
}
