import { useState } from "react";
import { trpc, errorMessage } from "../lib/trpc.ts";
import { useCan } from "../lib/auth.tsx";
import { PageHead, Card, Table, Badge, Button, Loading, ErrorBox, Tabs, Modal, Field, Input, Checkbox, useToast } from "../ui/kit.tsx";
export function MasterDataPage() {
  const [tab, setTab] = useState<"outlets" | "products">("outlets"); const can = useCan(); const toast = useToast();
  const outlets = trpc.masterData.outlets.useQuery(); const products = trpc.masterData.products.useQuery();
  const upO = trpc.masterData.upsertOutlet.useMutation({ onSuccess: () => outlets.refetch() }); const upP = trpc.masterData.upsertProduct.useMutation({ onSuccess: () => products.refetch() });
  const [o, setO] = useState<null | { code: string; retailer: string; branch: string; town: string; region: string; aliases: string; collectionPoint: boolean; active: boolean }>(null);
  const [p, setP] = useState<null | { sku: string; brand: string; name: string; packGrams: string; aliases: string; active: boolean }>(null);
  const [filter, setFilter] = useState("");
  return <>
    <PageHead title="Outlets & products" sub="Master data shared by campaigns. Campaign membership and collection points are set per campaign." actions={can("masterdata.write") && (tab === "outlets" ? <Button variant="primary" onClick={() => setO({ code: "", retailer: "", branch: "", town: "", region: "", aliases: "", collectionPoint: false, active: true })}>Add outlet</Button> : <Button variant="primary" onClick={() => setP({ sku: "", brand: "", name: "", packGrams: "2000", aliases: "", active: true })}>Add product</Button>)} />
    <Tabs tabs={[{ id: "outlets", label: `Outlets (${outlets.data?.length ?? 0})` }, { id: "products", label: `Products (${products.data?.length ?? 0})` }]} value={tab} onChange={setTab} />
    {tab === "outlets" && <Card actions={<Input placeholder="Filter…" value={filter} onChange={(e) => setFilter(e.target.value)} style={{ width: 240 }} />} title="Outlets">{outlets.isLoading ? <Loading /> : outlets.error ? <ErrorBox error={outlets.error} /> : <Table rows={(outlets.data ?? []).filter((x) => !filter || `${x.code} ${x.retailer} ${x.branch} ${x.town}`.toLowerCase().includes(filter.toLowerCase()))} keyOf={(x) => x.id} onRow={can("masterdata.write") ? (x) => setO({ code: x.code, retailer: x.retailer, branch: x.branch, town: x.town, region: x.region, aliases: x.aliases.join(" | "), collectionPoint: x.collectionPoint, active: x.active }) : undefined} cols={[{ h: "Code", c: (x) => <span className="mono">{x.code}</span> }, { h: "Retailer", c: (x) => x.retailer }, { h: "Branch", c: (x) => x.branch }, { h: "Town", c: (x) => x.town }, { h: "Region", c: (x) => x.region }, { h: "Aliases", c: (x) => <span className="small muted">{x.aliases.join(", ")}</span> }, { h: "Collection", c: (x) => x.collectionPoint ? "yes" : "" }, { h: "Active", c: (x) => x.active ? <Badge tone="success">active</Badge> : <Badge tone="danger">inactive</Badge> }, { h: "", c: (x) => x.sample ? <Badge tone="warning">sample</Badge> : null }]} />}</Card>}
    {tab === "products" && <Card title="Products">{products.isLoading ? <Loading /> : products.error ? <ErrorBox error={products.error} /> : <Table rows={products.data ?? []} keyOf={(x) => x.id} onRow={can("masterdata.write") ? (x) => setP({ sku: x.sku, brand: x.brand, name: x.name, packGrams: String(x.packGrams), aliases: x.aliases.join(" | "), active: x.active }) : undefined} cols={[{ h: "SKU", c: (x) => <span className="mono">{x.sku}</span> }, { h: "Brand", c: (x) => x.brand }, { h: "Name", c: (x) => x.name }, { h: "Pack", c: (x) => `${x.packGrams} g`, num: true }, { h: "Aliases", c: (x) => <span className="small muted">{x.aliases.join(", ")}</span> }, { h: "Active", c: (x) => x.active ? <Badge tone="success">active</Badge> : <Badge tone="danger">inactive</Badge> }, { h: "", c: (x) => x.sample ? <Badge tone="warning">sample</Badge> : null }]} />}</Card>}
    {o && <Modal title={o.code ? `Outlet ${o.code}` : "New outlet"} onClose={() => setO(null)} foot={<><Button onClick={() => setO(null)}>Cancel</Button><Button variant="primary" loading={upO.isPending} onClick={async () => { try { await upO.mutateAsync({ ...o, aliases: o.aliases.split("|").map((s) => s.trim()).filter(Boolean) }); setO(null); toast.push("Outlet saved", "success"); } catch (e) { toast.push(errorMessage(e), "error"); } }}>Save</Button></>}>
      <div className="tt-col"><div className="form-row"><Field label="Code"><Input value={o.code} onChange={(e) => setO({ ...o, code: e.target.value.toUpperCase() })} /></Field><Field label="Retailer"><Input value={o.retailer} onChange={(e) => setO({ ...o, retailer: e.target.value })} /></Field></div><div className="form-row"><Field label="Branch"><Input value={o.branch} onChange={(e) => setO({ ...o, branch: e.target.value })} /></Field><Field label="Town"><Input value={o.town} onChange={(e) => setO({ ...o, town: e.target.value })} /></Field><Field label="Region"><Input value={o.region} onChange={(e) => setO({ ...o, region: e.target.value })} /></Field></div><Field label="Aliases (| separated)" help="Names as printed on receipts, e.g. 'Mopani Westgate'"><Input value={o.aliases} onChange={(e) => setO({ ...o, aliases: e.target.value })} /></Field><div className="tt-row"><Checkbox label="Default collection point" checked={o.collectionPoint} onChange={(e) => setO({ ...o, collectionPoint: e.target.checked })} /><Checkbox label="Active" checked={o.active} onChange={(e) => setO({ ...o, active: e.target.checked })} /></div></div>
    </Modal>}
    {p && <Modal title={p.sku ? `Product ${p.sku}` : "New product"} onClose={() => setP(null)} foot={<><Button onClick={() => setP(null)}>Cancel</Button><Button variant="primary" loading={upP.isPending} onClick={async () => { try { await upP.mutateAsync({ sku: p.sku, brand: p.brand || undefined, name: p.name, packGrams: Number(p.packGrams), aliases: p.aliases.split("|").map((s) => s.trim()).filter(Boolean), active: p.active }); setP(null); toast.push("Product saved", "success"); } catch (e) { toast.push(errorMessage(e), "error"); } }}>Save</Button></>}>
      <div className="tt-col"><div className="form-row"><Field label="SKU"><Input value={p.sku} onChange={(e) => setP({ ...p, sku: e.target.value.toUpperCase() })} /></Field><Field label="Brand"><Input value={p.brand} onChange={(e) => setP({ ...p, brand: e.target.value })} /></Field></div><Field label="Name"><Input value={p.name} onChange={(e) => setP({ ...p, name: e.target.value })} /></Field><div className="form-row"><Field label="Pack size (grams)"><Input type="number" value={p.packGrams} onChange={(e) => setP({ ...p, packGrams: e.target.value })} /></Field></div><Field label="Aliases (| separated)" help="Receipt abbreviations, e.g. 'SV BROWN SUGAR'"><Input value={p.aliases} onChange={(e) => setP({ ...p, aliases: e.target.value })} /></Field><Checkbox label="Active" checked={p.active} onChange={(e) => setP({ ...p, active: e.target.checked })} /></div>
    </Modal>}
  </>;
}
