import { useState } from "react";
import { trpc, errorMessage, downloadAuth } from "../lib/trpc.ts";
import { useCan } from "../lib/auth.tsx";
import { PageHead, Card, Table, Badge, Button, Loading, ErrorBox, Tabs, KV, Select, Json, Input, Callout, useToast } from "../ui/kit.tsx";
import { fmtDate, titleCase, ago } from "../lib/format.ts";
type Tab = "health" | "queues" | "outbound" | "crm" | "alerts" | "exports" | "settings";
export function OpsPage() {
  const [tab, setTab] = useState<Tab>("health"); const can = useCan();
  return <>
    <PageHead title="Integrations & queues" sub="Provider modes are stated honestly; simulated or unconfigured providers are labelled." />
    <Tabs tabs={[{ id: "health", label: "Health" }, { id: "queues", label: "Queues & dead letters" }, { id: "outbound", label: "Outbound messages" }, { id: "crm", label: "CRM sync" }, { id: "alerts", label: "Alerts" }, { id: "exports", label: "Exports" }, ...(can("settings.write") || can("evidence.record") ? [{ id: "settings" as Tab, label: "Settings & evidence" }] : [])]} value={tab} onChange={setTab} />
    {tab === "health" && <Health />}{tab === "queues" && <Queues />}{tab === "outbound" && <Outbound />}{tab === "crm" && <Crm />}{tab === "alerts" && <Alerts />}{tab === "exports" && <Exports />}{tab === "settings" && <Settings />}
  </>;
}
function Health() {
  const q = trpc.ops.integrations.useQuery(undefined, { refetchInterval: 15_000 }); const m = trpc.ops.metrics.useQuery({ sinceHours: 24 });
  if (q.isLoading) return <Loading />; if (q.error) return <ErrorBox error={q.error} />; const d = q.data!;
  const mode = (x: { mode?: string; ok?: boolean }) => <Badge tone={x.ok === false ? "danger" : x.mode === "configured" || x.mode === "real" ? "success" : "warning"}>{x.mode ?? (x.ok ? "ok" : "not ok")}</Badge>;
  return <div className="tt-stack"><div className="tt-grid c3">
    <Card title="WhatsApp transport"><KV rows={[["Provider", d.transport.provider], ["Mode", mode(d.transport)], ["Note", (d.transport as { note?: string }).note ?? "–"], ["Outbound allowlist", d.outboundAllowlist.length ? d.outboundAllowlist.join(", ") : "none (non-production sends go to every recipient the simulator accepts)"]]} /></Card>
    <Card title="Receipt extractor"><KV rows={[["Provider", d.extractor.provider], ["Mode", mode(d.extractor)], ["Model", d.extractor.model ?? "–"], ["Note", d.extractor.note ?? d.extractor.error ?? "–"]]} /></Card>
    <Card title="CRM"><KV rows={[["Provider", d.crm.provider], ["Mode", mode(d.crm)], ["Note", d.crm.note ?? d.crm.error ?? "–"], ["Queue", Object.entries(d.crmQueue.byStatus).map(([k, n]) => `${k} ${n}`).join(" · ") || "empty"]]} /></Card>
    <Card title="Storage & database"><KV rows={[["Storage", `${d.storage.ok ? "ok" : "NOT OK"} · ${(d.storage as { detail?: string }).detail ?? ""}`], ["Database", d.database.url], ["Environment", d.environment]]} /></Card>
    <Card title="Worker"><KV rows={[["Mode", d.workerMode], ["Running in this process", d.worker.running ? "yes" : "no"], ["Ticks", d.worker.ticks], ["Last tick", ago(d.worker.lastTickAt)]]} /></Card>
    <Card title="Queues"><KV rows={[["Inbound events", Object.entries(d.queues.events).map(([k, n]) => `${k} ${n}`).join(" · ") || "empty"], ["Jobs", Object.entries(d.queues.jobs).map(([k, n]) => `${k} ${n}`).join(" · ") || "empty"], ["Oldest waiting event", ago(d.queues.oldestEvent)], ["Outbound", Object.entries(d.outbound.byStatus).map(([k, n]) => `${k} ${n}`).join(" · ") || "empty"]]} /></Card>
  </div>
  <Card title="Metrics, last 24 hours">{m.data && <Table rows={m.data} keyOf={(r) => r.name} cols={[{ h: "Metric", c: (r) => <span className="mono">{r.name}</span> }, { h: "Events", c: (r) => r.n, num: true }, { h: "Sum", c: (r) => r.sum, num: true }]} empty="No metrics recorded yet." />}</Card></div>;
}
function Queues() {
  const q = trpc.ops.queues.useQuery(undefined, { refetchInterval: 15_000 }); const can = useCan(); const toast = useToast(); const replay = trpc.ops.replayEvent.useMutation({ onSuccess: () => q.refetch() }); const retry = trpc.ops.retryJob.useMutation({ onSuccess: () => q.refetch() });
  if (q.isLoading) return <Loading />; if (q.error) return <ErrorBox error={q.error} />; const d = q.data!;
  return <div className="tt-stack">
    <div className="tt-grid c2"><Card title="Inbound events"><KV rows={Object.entries(d.stats.events).map(([k, n]) => [titleCase(k), n])} /><p className="small muted">Oldest waiting: {ago(d.stats.oldestEvent)}</p></Card><Card title="Jobs"><KV rows={Object.entries(d.stats.jobs).map(([k, n]) => [titleCase(k), n])} /><p className="small muted">Oldest waiting: {ago(d.stats.oldestJob)}</p></Card></div>
    <Card title="Failed / dead inbound events"><Table rows={d.events} keyOf={(e) => e.id} cols={[{ h: "Event", c: (e) => <span className="mono small">{e.id}</span> }, { h: "Kind", c: (e) => e.kind }, { h: "Status", c: (e) => <Badge status={e.status} /> }, { h: "Attempts", c: (e) => e.attempts, num: true }, { h: "Error", c: (e) => <span className="small">{e.error}</span> }, { h: "Received", c: (e) => fmtDate(e.receivedAt) }, { h: "", c: (e) => can("ops.retry") ? <Button size="sm" onClick={async () => { try { await replay.mutateAsync({ id: e.id }); toast.push("Replayed", "success"); } catch (e2) { toast.push(errorMessage(e2), "error"); } }}>Replay</Button> : null }]} empty="No failed events." /></Card>
    <Card title="Failed / dead jobs"><Table rows={d.jobs} keyOf={(j) => j.id} cols={[{ h: "Job", c: (j) => <span className="mono small">{j.id}</span> }, { h: "Kind", c: (j) => j.kind }, { h: "Status", c: (j) => <Badge status={j.status} /> }, { h: "Attempts", c: (j) => j.attempts, num: true }, { h: "Error", c: (j) => <span className="small">{j.lastError}</span> }, { h: "Created", c: (j) => fmtDate(j.createdAt) }, { h: "", c: (j) => can("ops.retry") ? <Button size="sm" onClick={async () => { try { await retry.mutateAsync({ id: j.id }); toast.push("Retried", "success"); } catch (e2) { toast.push(errorMessage(e2), "error"); } }}>Retry</Button> : null }]} empty="No failed jobs." /></Card>
  </div>;
}
function Outbound() {
  const [status, setStatus] = useState(""); const q = trpc.ops.outbound.useQuery({ status: status || undefined }, { refetchInterval: 15_000 }); const can = useCan(); const toast = useToast(); const retry = trpc.ops.retryOutbound.useMutation({ onSuccess: () => q.refetch() });
  return <Card title="Outbound messages" actions={<Select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Any status</option>{["pending", "sent", "delivered", "read", "retryable_failure", "permanent_failure", "unknown_outcome"].map((s) => <option key={s} value={s}>{titleCase(s)}</option>)}</Select>}>
    {q.isLoading ? <Loading /> : q.error ? <ErrorBox error={q.error} /> : <Table rows={q.data ?? []} keyOf={(m) => m.id} cols={[{ h: "To", c: (m) => <span className="mono">{m.channelUid}</span> }, { h: "Purpose", c: (m) => titleCase(m.purpose) }, { h: "Kind", c: (m) => m.kind }, { h: "Status", c: (m) => <Badge status={m.status} /> }, { h: "Attempts", c: (m) => m.attempts, num: true }, { h: "Error", c: (m) => <span className="small">{m.errorCode ? `${m.errorCode}: ` : ""}{m.lastError ?? ""}</span> }, { h: "Next attempt", c: (m) => fmtDate(m.nextAttemptAt) }, { h: "Created", c: (m) => fmtDate(m.createdAt) }, { h: "", c: (m) => can("ops.retry") && ["retryable_failure", "permanent_failure", "unknown_outcome"].includes(m.status) ? <Button size="sm" onClick={async () => { try { await retry.mutateAsync({ id: m.id }); toast.push("Queued again", "success"); } catch (e) { toast.push(errorMessage(e), "error"); } }}>Retry</Button> : null }]} empty="No messages for this filter." />}
    <p className="small muted" style={{ marginTop: 8 }}>Unknown outcomes are never re-sent automatically: confirm with the provider or the participant before retrying, to avoid duplicate messages.</p>
  </Card>;
}
function Crm() {
  const [status, setStatus] = useState(""); const q = trpc.ops.crmEvents.useQuery({ status: status || undefined }, { refetchInterval: 15_000 }); const can = useCan(); const toast = useToast(); const retry = trpc.ops.retryCrm.useMutation({ onSuccess: () => q.refetch() }); const reconcile = trpc.ops.reconcileCrm.useMutation({ onSuccess: () => q.refetch() }); const [type, setType] = useState("entry"); const preview = trpc.ops.crmPreview.useQuery({ type });
  return <div className="tt-stack">
    <Card title="CRM events" actions={<><Select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Any status</option>{["pending", "sending", "delivered", "retryable_failure", "permanent_failure", "unknown_outcome", "reconciled"].map((s) => <option key={s} value={s}>{titleCase(s)}</option>)}</Select>{can("ops.retry") && <Button size="sm" loading={reconcile.isPending} onClick={async () => { try { const r = await reconcile.mutateAsync(); toast.push(`Reconciled ${r.reconciled}, requeued ${r.requeued} of ${r.checked} checked`, "success"); } catch (e) { toast.push(errorMessage(e), "error"); } }}>Reconcile with vendor</Button>}</>}>
      {q.isLoading ? <Loading /> : q.error ? <ErrorBox error={q.error} /> : <Table rows={q.data ?? []} keyOf={(e) => e.id} cols={[{ h: "Entity", c: (e) => <><Badge>{e.entityType}</Badge> <span className="mono small">{e.entityId}</span> v{e.entityVersion}</> }, { h: "Key", c: (e) => <span className="mono small">{e.externalKey}</span> }, { h: "Status", c: (e) => <Badge status={e.status} /> }, { h: "Attempts", c: (e) => e.attempts, num: true }, { h: "Error", c: (e) => <span className="small">{e.lastError ?? ""}</span> }, { h: "Delivered", c: (e) => fmtDate(e.deliveredAt) }, { h: "", c: (e) => can("ops.retry") && ["retryable_failure", "permanent_failure", "unknown_outcome"].includes(e.status) ? <Button size="sm" onClick={async () => { try { await retry.mutateAsync({ id: e.id }); toast.push("Queued again", "success"); } catch (e2) { toast.push(errorMessage(e2), "error"); } }}>Retry</Button> : null }]} empty="No CRM events for this filter." />}
    </Card>
    <Card title="Canonical mapping preview" actions={<Select value={type} onChange={(e) => setType(e.target.value)}>{["participant", "enrollment", "submission", "entry", "winner", "claim"].map((t) => <option key={t} value={t}>{t}</option>)}</Select>}><p className="small muted">What the CRM receives for each entity type (mapping version is part of every record). Identity numbers and full phone numbers are never included.</p>{preview.data && <Json value={preview.data} />}</Card>
  </div>;
}
function Alerts() {
  const [all, setAll] = useState(false); const q = trpc.ops.alerts.useQuery({ all }, { refetchInterval: 15_000 }); const can = useCan(); const ack = trpc.ops.ackAlert.useMutation({ onSuccess: () => q.refetch() });
  return <Card title="Alerts" actions={<Button size="sm" onClick={() => setAll(!all)}>{all ? "Open only" : "Include acknowledged"}</Button>}>{q.isLoading ? <Loading /> : q.error ? <ErrorBox error={q.error} /> : <Table rows={q.data ?? []} keyOf={(a) => a.id} cols={[{ h: "Severity", c: (a) => <Badge status={a.severity} /> }, { h: "Kind", c: (a) => <span className="mono">{a.kind}</span> }, { h: "Message", c: (a) => <>{a.message}{a.runbook && <div className="small muted">Runbook: {a.runbook}</div>}</> }, { h: "Raised", c: (a) => fmtDate(a.createdAt) }, { h: "Acknowledged", c: (a) => a.ackedAt ? `${fmtDate(a.ackedAt)} by ${a.ackedBy}` : "" }, { h: "", c: (a) => !a.ackedAt && can("ops.alerts.ack") ? <Button size="sm" onClick={() => ack.mutate({ id: a.id })}>Acknowledge</Button> : null }]} empty="No alerts." />}</Card>;
}
function Exports() {
  const can = useCan(); const toast = useToast(); const campaigns = trpc.campaigns.list.useQuery(); const [cid, setCid] = useState(""); const [busy, setBusy] = useState<string | null>(null);
  if (!can("report.export")) return <Callout>Exports are limited to the auditor role. Every export is watermarked with the exporting user and recorded in the audit log.</Callout>;
  return <Card title="Exports (CSV, formula-safe, watermarked)" actions={<Select value={cid} onChange={(e) => setCid(e.target.value)}><option value="">Current campaign</option>{campaigns.data?.map((c) => <option key={c.id} value={c.id}>{c.code}</option>)}</Select>}>
    <div className="tt-row">{["submissions", "entries", "winners", "participants", "outlets"].map((s) => <Button key={s} loading={busy === s} onClick={async () => { setBusy(s); try { await downloadAuth(`/api/export/${s}.csv${cid ? `?campaignId=${cid}` : ""}`, `${s}.csv`); } catch (e) { toast.push(errorMessage(e), "error"); } finally { setBusy(null); } }}>{titleCase(s)}</Button>)}</div>
    <p className="small muted" style={{ marginTop: 8 }}>Identity numbers and full phone numbers are never exported.</p>
  </Card>;
}
function Settings() {
  const can = useCan(); const toast = useToast(); const [key, setKey] = useState("review.sla_hours"); const q = trpc.ops.setting.useQuery({ key }, { enabled: /^[a-z0-9_.:-]{1,80}$/.test(key) }); const set = trpc.ops.setSetting.useMutation({ onSuccess: () => q.refetch() }); const [val, setVal] = useState(""); const record = trpc.ops.recordEvidence.useMutation(); const readiness = trpc.readiness.get.useQuery();
  return <div className="tt-grid c2">
    {can("settings.write") && <Card title="Settings"><div className="tt-col"><Input value={key} onChange={(e) => setKey(e.target.value)} mono placeholder="setting key" /><div className="small muted">Current: <span className="mono">{JSON.stringify(q.data ?? null)}</span></div><Input value={val} onChange={(e) => setVal(e.target.value)} mono placeholder='new value (JSON, e.g. 24 or "text")' /><div><Button variant="primary" loading={set.isPending} onClick={async () => { try { await set.mutateAsync({ key, value: JSON.parse(val) }); toast.push("Saved", "success"); } catch (e) { toast.push(errorMessage(e), "error"); } }}>Save</Button></div></div></Card>}
    {can("evidence.record") && <Card title="Record readiness evidence"><p className="small muted">Records that a piece of evidence exists and was accepted (link to the artefact). Feeds the activation validator.</p><div className="tt-col">{(["receipt_benchmark_accepted", "restore_rehearsal", "load_benchmark", "client_uat_signoff"] as const).map((k) => { const v = readiness.data?.evidence.find((e) => e.kind === k)?.value as { at?: string } | null | undefined; return <div key={k} className="tt-row"><span className="mono" style={{ minWidth: 240 }}>{k}</span>{v ? <Badge tone="success">recorded {fmtDate(v.at)}</Badge> : <Badge tone="warning">missing</Badge>}<Button size="sm" onClick={async () => { const ref = prompt("Reference to the evidence (path, link or ticket):"); if (ref == null) return; try { await record.mutateAsync({ kind: k, detail: { reference: ref } }); readiness.refetch(); toast.push("Recorded", "success"); } catch (e) { toast.push(errorMessage(e), "error"); } }}>Record</Button></div>; })}</div></Card>}
  </div>;
}
