import { useState } from "react";
import { trpc, errorMessage } from "../lib/trpc.ts";
import { PageHead, Card, Table, Button, Badge, Loading, ErrorBox, ActionDialog, Modal, useToast, Checkbox, Field, Input, Tabs } from "../ui/kit.tsx";
import { fmtDate } from "../lib/format.ts";
export function StaffPage() {
  const q = trpc.staff.list.useQuery(); const toast = useToast(); const [tab, setTab] = useState<"users" | "matrix">("users");
  const create = trpc.staff.create.useMutation({ onSuccess: () => q.refetch() }); const update = trpc.staff.update.useMutation({ onSuccess: () => q.refetch() }); const reset = trpc.staff.resetPassword.useMutation({ onSuccess: () => q.refetch() });
  const [dialog, setDialog] = useState<null | { kind: "create" } | { kind: "roles"; id: string; roles: string[] } | { kind: "temp"; email: string; pw: string }>(null);
  const [form, setForm] = useState({ email: "", name: "", roles: [] as string[] });
  if (q.isLoading) return <Loading />; if (q.error) return <ErrorBox error={q.error} />; const d = q.data!;
  return <>
    <PageHead title="Access" sub="Staff accounts, roles and the permission matrix. New accounts get a one-time temporary password." actions={<Button variant="primary" onClick={() => setDialog({ kind: "create" })}>Add staff member</Button>} />
    <Tabs tabs={[{ id: "users", label: "Users" }, { id: "matrix", label: "Permission matrix" }]} value={tab} onChange={setTab} />
    {tab === "users" && <Card flush><Table rows={d.users} keyOf={(u) => u.id} cols={[{ h: "Name", c: (u) => <><div className="strong">{u.name}</div><div className="small muted">{u.email}</div></> }, { h: "Roles", c: (u) => u.roles.map((r) => <Badge key={r}>{r}</Badge>) }, { h: "Status", c: (u) => <Badge status={u.status} /> }, { h: "MFA", c: (u) => u.mfaEnabled ? <Badge tone="success">on</Badge> : <Badge>off</Badge> }, { h: "Password", c: (u) => u.mustChangePassword ? <Badge tone="warning">temporary</Badge> : "set" }, { h: "Last sign-in", c: (u) => fmtDate(u.lastLoginAt) }, { h: "", c: (u) => <div className="tt-row"><Button size="sm" onClick={() => setDialog({ kind: "roles", id: u.id, roles: u.roles })}>Roles</Button><Button size="sm" onClick={async () => { try { await update.mutateAsync({ userId: u.id, status: u.status === "active" ? "disabled" : "active" }); toast.push("Updated", "success"); } catch (e) { toast.push(errorMessage(e), "error"); } }}>{u.status === "active" ? "Disable" : "Enable"}</Button><Button size="sm" onClick={async () => { try { const r = await reset.mutateAsync({ userId: u.id }); setDialog({ kind: "temp", email: u.email, pw: r.temporaryPassword }); } catch (e) { toast.push(errorMessage(e), "error"); } }}>Reset password</Button></div> }]} /></Card>}
    {tab === "matrix" && <Card flush><div className="tt-table-wrap"><table className="tt-table"><thead><tr><th>Permission</th>{d.roles.map((r) => <th key={r}>{r}</th>)}</tr></thead><tbody>{d.matrix.map((row) => <tr key={row.permission}><td className="mono">{row.permission}</td>{d.roles.map((r) => <td key={r} style={{ textAlign: "center" }}>{(row.roles as readonly string[]).includes(r) ? "●" : ""}</td>)}</tr>)}</tbody></table></div></Card>}
    {dialog?.kind === "create" && <Modal title="Add staff member" onClose={() => setDialog(null)} foot={<><Button onClick={() => setDialog(null)}>Cancel</Button><Button variant="primary" loading={create.isPending} disabled={!form.email || !form.name || !form.roles.length} onClick={async () => { try { const r = await create.mutateAsync(form); setForm({ email: "", name: "", roles: [] }); setDialog({ kind: "temp", email: r.user.email, pw: r.temporaryPassword ?? "" }); } catch (e) { toast.push(errorMessage(e), "error"); } }}>Create</Button></>}>
      <div className="tt-col"><Field label="Email"><Input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></Field><Field label="Name"><Input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><Field label="Roles" help="Separation of duties: draw officer and draw approver must be different people; the technical administrator holds no campaign rights."><div className="tt-col" style={{ gap: 6 }}>{d.roles.map((r) => <Checkbox key={r} label={r} checked={form.roles.includes(r)} onChange={(e) => setForm({ ...form, roles: e.target.checked ? [...form.roles, r] : form.roles.filter((x) => x !== r) })} />)}</div></Field></div>
    </Modal>}
    {dialog?.kind === "roles" && <RolesDialog roles={[...d.roles]} value={dialog.roles} onClose={() => setDialog(null)} onSave={async (roles) => { await update.mutateAsync({ userId: dialog.id, roles }); toast.push("Roles updated; the user's sessions were revoked", "success"); }} />}
    {dialog?.kind === "temp" && <Modal title="Temporary password" onClose={() => setDialog(null)} foot={<Button variant="primary" onClick={() => setDialog(null)}>Done</Button>}><p>Hand this to <strong>{dialog.email}</strong> through a separate channel. It is shown once and must be changed at first sign-in.</p><pre>{dialog.pw}</pre></Modal>}
  </>;
}
function RolesDialog({ roles, value, onClose, onSave }: { roles: string[]; value: string[]; onClose: () => void; onSave: (r: string[]) => Promise<void> }) { const [sel, setSel] = useState(value); return <ActionDialog title="Change roles" description={<div className="tt-col" style={{ gap: 6 }}>{roles.map((r) => <Checkbox key={r} label={r} checked={sel.includes(r)} onChange={(e) => setSel(e.target.checked ? [...sel, r] : sel.filter((x) => x !== r))} />)}</div>} confirmLabel="Save roles" onConfirm={() => onSave(sel)} onClose={onClose} />; }
