import { useState } from "react";
import { trpc, errorMessage } from "../lib/trpc.ts";
import { useCan } from "../lib/auth.tsx";
import { Link, navigate, useQueryParams } from "../lib/router.tsx";
import { PageHead, Card, Table, Badge, Button, Loading, ErrorBox, Input, Select, KV, Tabs, ActionDialog, AuthImage, Json, Callout, useToast } from "../ui/kit.tsx";
import { fmtDate, titleCase, money } from "../lib/format.ts";
import { REASON_TEXT } from "@promo/core/conversation/copy.ts";
const STATUSES = ["", "received", "processing", "delayed", "review", "qualified", "not_qualified", "duplicate", "reupload"];
export function SubmissionsPage() {
  const params = useQueryParams(); const [tab, setTab] = useState<"queue" | "all">(params.get("tab") === "queue" ? "queue" : "all");
  const [f, setF] = useState({ status: params.get("status") ?? "", reference: "", period: "" }); const [offset, setOffset] = useState(0);
  const campaigns = trpc.campaigns.list.useQuery(); const [cid, setCid] = useState("");
  const list = trpc.submissions.list.useQuery({ campaignId: cid || undefined, status: f.status || undefined, reference: f.reference || undefined, period: f.period || undefined, limit: 50, offset }, { enabled: tab === "all" });
  const queue = trpc.submissions.queue.useQuery(undefined, { enabled: tab === "queue", refetchInterval: 20_000 });
  return <>
    <PageHead title="Submissions & review" sub="Every receipt upload with its decision; the queue holds what needs a human." />
    <Tabs tabs={[{ id: "queue", label: `Review queue${queue.data ? ` (${queue.data.count})` : ""}` }, { id: "all", label: "All submissions" }]} value={tab} onChange={setTab} />
    {tab === "queue" && <Card title={queue.data ? <h2>Open reviews · {queue.data.overdue} past target · {Object.entries(queue.data.byReason).map(([k, n]) => `${titleCase(k)} ${n}`).join(" · ")}</h2> : "Open reviews"}>{queue.isLoading ? <Loading /> : queue.error ? <ErrorBox error={queue.error} /> : <Table rows={queue.data!.items} keyOf={(x) => x.submissionId} onRow={(x) => navigate(`/submissions/${x.submissionId}`)} cols={[{ h: "Reference", c: (x) => <span className="mono">{x.reference}</span> }, { h: "Reason", c: (x) => titleCase(x.reason) }, { h: "State", c: (x) => <Badge status={x.state} /> }, { h: "Assignee", c: (x) => x.assignee ?? "–" }, { h: "Period", c: (x) => x.period ?? "–" }, { h: "Age", c: (x) => `${x.ageMinutes} min`, num: true }, { h: "Target", c: (x) => fmtDate(x.slaDueAt) }]} empty="Nothing waiting for review." />}</Card>}
    {tab === "all" && <Card title={<div className="tt-row"><Select value={cid} onChange={(e) => { setOffset(0); setCid(e.target.value); }} style={{ width: 200 }}><option value="">All campaigns</option>{campaigns.data?.map((c) => <option key={c.id} value={c.id}>{c.code}</option>)}</Select><Select value={f.status} onChange={(e) => { setOffset(0); setF({ ...f, status: e.target.value }); }} style={{ width: 170 }}>{STATUSES.map((s) => <option key={s} value={s}>{s ? titleCase(s) : "Any status"}</option>)}</Select><Input placeholder="Reference" value={f.reference} onChange={(e) => { setOffset(0); setF({ ...f, reference: e.target.value }); }} style={{ width: 160 }} /><Input placeholder="Period" value={f.period} onChange={(e) => { setOffset(0); setF({ ...f, period: e.target.value }); }} style={{ width: 100 }} /></div>}>
      {list.isLoading ? <Loading /> : list.error ? <ErrorBox error={list.error} /> : <Table rows={list.data!.rows} keyOf={(s) => s.id} onRow={(s) => navigate(`/submissions/${s.id}`)} cols={[{ h: "Reference", c: (s) => <span className="mono">{s.reference}</span> }, { h: "Status", c: (s) => <Badge status={s.status} /> }, { h: "Reason", c: (s) => titleCase(s.reasonCode) }, { h: "Period", c: (s) => s.periodCode ?? "–" }, { h: "Review", c: (s) => s.review ? <Badge status={s.review.state} /> : "" }, { h: "Received", c: (s) => fmtDate(s.intakeAt) }, { h: "Decided", c: (s) => fmtDate(s.decidedAt) }]} />}
      <div className="tt-row" style={{ marginTop: 12 }}><Button size="sm" disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - 50))}>Previous</Button><Button size="sm" disabled={!list.data?.next} onClick={() => setOffset(list.data!.next!)}>Next</Button></div>
    </Card>}
  </>;
}
export function SubmissionDetailPage({ id }: { id: string }) {
  const q = trpc.submissions.get.useQuery({ submissionId: id }); const can = useCan(); const toast = useToast(); const utils = trpc.useUtils(); const refresh = () => { utils.submissions.get.invalidate({ submissionId: id }); utils.submissions.queue.invalidate(); };
  const assign = trpc.submissions.assign.useMutation({ onSuccess: refresh }); const release = trpc.submissions.release.useMutation({ onSuccess: refresh }); const escalate = trpc.submissions.escalate.useMutation({ onSuccess: refresh }); const review = trpc.submissions.review.useMutation({ onSuccess: refresh }); const correct = trpc.submissions.correctFacts.useMutation({ onSuccess: refresh }); const resolve = trpc.submissions.resolveDuplicate.useMutation({ onSuccess: refresh }); const reprocess = trpc.submissions.reprocess.useMutation({ onSuccess: refresh }); const resend = trpc.submissions.resendResult.useMutation();
  const [dialog, setDialog] = useState<null | "qualified" | "not_qualified" | "duplicate" | "reupload" | "escalate" | "correct" | "reprocess">(null); const [normalised, setNormalised] = useState(false);
  if (q.isLoading) return <Loading />; if (q.error) return <ErrorBox error={q.error} />; const d = q.data!; const s = d.submission; const last = d.extractions.at(-1); const facts = (last?.facts ?? {}) as { transaction?: Record<string, unknown>; merchant?: { text?: string; candidates?: Array<{ outletId: string; score: number; label?: string }> }; document?: { kind?: string; score?: number }; lines?: Array<{ raw: string; quantity?: number | null; product?: { code: string } | null; voided?: boolean; packGrams?: number | null }>; quality?: { confidence?: number | null; warnings?: string[] } };
  const rules = (last?.ruleResults ?? []) as Array<{ rule: string; outcome: string; reason?: string | null; detail?: unknown }>; const open = d.review && d.review.state !== "decided"; const reviewer = can("submission.review");
  return <>
    <PageHead title={<><span className="mono">{s.reference}</span> <Badge status={s.status} /></>} sub={<>{titleCase(s.reasonCode) || "–"} · received {fmtDate(s.intakeAt)} · period {s.periodCode ?? "none"} · <Link to="/submissions">All submissions</Link></>} actions={<>
      {open && reviewer && !d.review?.assignee && <Button onClick={() => assign.mutate({ submissionId: id })}>Take this review</Button>}
      {open && reviewer && d.review?.assignee && <Button onClick={() => release.mutate({ submissionId: id })}>Release</Button>}
      {open && reviewer && <Button onClick={() => setDialog("escalate")}>Escalate</Button>}
      {s.status !== "qualified" && can("submission.reprocess") && <Button onClick={() => setDialog("reprocess")}>Reprocess</Button>}
      {can("support.handoff") && ["qualified", "not_qualified", "duplicate", "reupload"].includes(s.status) && <Button onClick={async () => { try { await resend.mutateAsync({ submissionId: id }); toast.push("Result message queued again", "success"); } catch (e) { toast.push(errorMessage(e), "error"); } }}>Resend result</Button>}
    </>} />
    {open && reviewer && <Callout tone="info"><div className="tt-row"><strong>Decision:</strong><Button variant="primary" size="sm" onClick={() => setDialog("qualified")}>Qualify (award entry)</Button><Button size="sm" onClick={() => setDialog("not_qualified")}>Not qualified</Button><Button size="sm" onClick={() => setDialog("duplicate")}>Duplicate</Button><Button size="sm" onClick={() => setDialog("reupload")}>Ask for a new photo</Button><Button size="sm" variant="ghost" onClick={() => setDialog("correct")}>Correct facts</Button><span className="muted small">Review state: {d.review?.state}{d.review?.assignee ? ` · ${d.review.assignee}` : ""} · target {fmtDate(d.review?.slaDueAt)}</span></div></Callout>}
    <div className="tt-grid c2" style={{ marginTop: 16 }}>
      <Card title="Receipt image" actions={d.media?.viewable && <Button size="sm" onClick={() => setNormalised(!normalised)}>{normalised ? "Original" : "Normalised"}</Button>}>
        {d.media ? d.media.viewable ? <AuthImage src={`/api/media/${id}${normalised ? "?v=normalised" : ""}`} alt={`Receipt ${s.reference}`} /> : <Callout>Your role does not include receipt images.</Callout> : <Callout>No image stored.</Callout>}
        {d.media && <div className="small muted" style={{ marginTop: 8 }}>{d.media.width}×{d.media.height} · {d.media.mime} · {Math.round((d.media.bytes ?? 0) / 1024)} KiB · quality {JSON.stringify(d.media.quality ?? {})}</div>}
      </Card>
      <div className="tt-col">
        <Card title="What was read">
          <KV rows={[["Document", `${facts.document?.kind ?? "–"} (score ${facts.document?.score ?? "–"})`], ["Merchant header", facts.merchant?.text ?? "–"], ["Selected outlet", d.outlet ? `${d.outlet.retailer} — ${d.outlet.branch}, ${d.outlet.town} (${d.outlet.code})` : "–"], ["Outlet candidates", (facts.merchant?.candidates ?? []).map((c) => `${c.outletId} ${(c.score * 100).toFixed(0)}%`).join(", ") || "none"], ["Receipt number", <span className="mono">{String(facts.transaction?.receiptNo ?? "–")}</span>], ["Date", `${facts.transaction?.date ?? "–"}${facts.transaction?.dateAmbiguous ? " (ambiguous day/month)" : ""}`], ["Total", money(facts.transaction?.totalMinor as number | null)], ["Confidence", facts.quality?.confidence != null ? `${Math.round((facts.quality.confidence as number) * 100)}%` : "–"], ["Extractor", last ? `${last.provider} · ${last.model} · attempt ${last.attemptNo}` : "–"], ["Warnings", (facts.quality?.warnings ?? []).join("; ") || "none"]]} />
          {facts.lines && facts.lines.length > 0 && <div style={{ marginTop: 12 }}><h4>Line items</h4><Table rows={facts.lines.map((l, i) => ({ ...l, i }))} keyOf={(l) => String(l.i)} cols={[{ h: "Line", c: (l) => <span className="mono small">{l.raw}</span> }, { h: "Product", c: (l) => l.product?.code ?? "" }, { h: "Qty", c: (l) => l.quantity ?? "?", num: true }, { h: "Pack", c: (l) => l.packGrams ? `${l.packGrams} g` : "" }, { h: "", c: (l) => l.voided ? <Badge tone="danger">void</Badge> : null }]} /></div>}
        </Card>
        <Card title="Rule results"><div className="rule-list">{rules.map((r) => <div key={r.rule}><Badge status={r.outcome === "pass" ? "pass" : r.outcome === "fail" ? "fail" : "review"}>{r.outcome}</Badge><span className="mono">{r.rule}</span>{r.reason && <span className="muted">{REASON_TEXT[r.reason] ?? r.reason}</span>}</div>)}{!rules.length && <span className="muted">No rule evaluation recorded yet.</span>}</div></Card>
      </div>
      <Card title="Identity & ledger"><KV rows={[["Participant", d.participant ? <Link to={`/participants/${d.participant.id}`}>{d.participant.firstName} {d.participant.surname} · {d.participant.phone}</Link> : "–"], ["Canonical receipt", d.canonical ? <span className="mono small">{d.canonical.receiptKey} · {d.canonical.status}</span> : "none (identity incomplete or not a receipt)"], ["Entry", d.entry ? <Link to={`/entries/${d.entry.id}`}>{d.entry.id} · {d.entry.status}</Link> : "none"], ["Rules version", d.rulesVersion ? `v${d.rulesVersion.versionNo} · ${d.rulesVersion.configHash.slice(0, 12)}…` : "–"], ["Decided", `${fmtDate(s.decidedAt)}${s.decidedBy ? ` by ${s.decidedBy}` : ""}`], ["Re-upload of", s.reuploadOf ? <Link to={`/submissions/${s.reuploadOf}`}>{s.reuploadOf}</Link> : "–"], ["Related attempts", d.attempts.length ? d.attempts.map((a) => <div key={a.id}><Link to={`/submissions/${a.id}`}>{a.reference}</Link> <Badge status={a.status} /></div>) : "–"]]} /></Card>
      <Card title={`Duplicate candidates (${d.duplicates.length})`}>
        <Table rows={d.duplicates} keyOf={(x) => x.id} cols={[{ h: "Candidate", c: (x) => <Link to={`/submissions/${x.candidateSubmissionId}`}>{x.candidateReference}</Link> }, { h: "Kind", c: (x) => titleCase(x.kind) }, { h: "Score", c: (x) => ((x.score ?? 0) * 100).toFixed(0) + "%", num: true }, { h: "Same person", c: (x) => x.sameParticipant ? "yes" : <Badge tone="warning">no</Badge> }, { h: "Resolution", c: (x) => x.resolution ? <Badge tone={x.resolution === "same_purchase" ? "warning" : "success"}>{titleCase(x.resolution)}</Badge> : reviewer && open ? <div className="tt-row"><Button size="sm" onClick={() => resolve.mutate({ candidateId: x.id, resolution: "same_purchase" })}>Same purchase</Button><Button size="sm" onClick={() => resolve.mutate({ candidateId: x.id, resolution: "different_purchase" })}>Different</Button></div> : "open" }]} empty="No duplicate signals." />
      </Card>
      <Card title="Extraction attempts"><Table rows={d.extractions} keyOf={(x) => x.id} cols={[{ h: "#", c: (x) => x.attemptNo, num: true }, { h: "Provider", c: (x) => `${x.provider} · ${x.model}` }, { h: "Disposition", c: (x) => x.disposition ? <Badge status={x.disposition} /> : "–" }, { h: "Latency", c: (x) => x.latencyMs != null ? `${x.latencyMs} ms` : "–" }, { h: "Error", c: (x) => x.error ?? "" }, { h: "When", c: (x) => fmtDate(x.createdAt) }]} />
        {last?.ocrText && <details style={{ marginTop: 12 }}><summary className="small muted">OCR text</summary><pre>{last.ocrText}</pre></details>}
        {last?.raw && <details style={{ marginTop: 8 }}><summary className="small muted">Raw extractor output</summary><Json value={last.raw} /></details>}
      </Card>
    </div>
    {(dialog === "qualified" || dialog === "not_qualified" || dialog === "duplicate" || dialog === "reupload") && <ActionDialog title={`Decide: ${titleCase(dialog)}`} description={dialog === "qualified" ? "Awards one entry now (unless the receipt is already credited, in which case it becomes a duplicate). The participant is told." : "The participant receives the after-review message with this reason."} confirmLabel={titleCase(dialog)} fields={[...(dialog === "qualified" ? [] : [{ key: "reasonCode", label: "Reason code", type: "select" as const, required: true, options: Object.keys(REASON_TEXT).map((k) => ({ value: k, label: `${k} — ${REASON_TEXT[k]}` })) }]), { key: "note", label: "Reviewer note", type: "textarea" as const }]} onConfirm={async (v) => { await review.mutateAsync({ submissionId: id, decision: dialog, reasonCode: v.reasonCode || undefined, note: v.note || undefined, expectedVersion: s.version }); toast.push("Decision recorded", "success"); }} onClose={() => setDialog(null)} />}
    {dialog === "escalate" && <ActionDialog title="Escalate" fields={[{ key: "note", label: "Why", type: "textarea", required: true }]} onConfirm={async (v) => { await escalate.mutateAsync({ submissionId: id, note: v.note }); }} onClose={() => setDialog(null)} />}
    {dialog === "correct" && <ActionDialog title="Correct readable facts" description="Recorded as a manual extraction attempt with your note; used for the identity key when you then qualify." fields={[{ key: "receiptNo", label: "Receipt number" }, { key: "date", label: "Date (YYYY-MM-DD)" }, { key: "total", label: "Total (e.g. 6.20)" }, { key: "note", label: "Note", required: true }]} confirmLabel="Save correction" onConfirm={async (v) => { await correct.mutateAsync({ submissionId: id, receiptNo: v.receiptNo || undefined, date: v.date || undefined, totalMinor: v.total ? Math.round(Number(v.total) * 100) : undefined, note: v.note }); toast.push("Facts corrected", "success"); }} onClose={() => setDialog(null)} />}
    {dialog === "reprocess" && <ActionDialog title="Reprocess submission" description="Runs extraction and rules again through the normal path. Credited submissions cannot be reprocessed." fields={[{ key: "reason", label: "Reason", required: true }]} onConfirm={async (v) => { await reprocess.mutateAsync({ submissionId: id, reason: v.reason }); toast.push("Queued for reprocessing", "success"); }} onClose={() => setDialog(null)} />}
  </>;
}
