import { useState } from "react";
import { trpc, errorMessage } from "../lib/trpc.ts";
import { useCan } from "../lib/auth.tsx";
import { Link, navigate } from "../lib/router.tsx";
import { PageHead, Card, Table, Badge, Button, Loading, ErrorBox, Select, KV, ActionDialog, Callout, useToast } from "../ui/kit.tsx";
import { fmtDate, titleCase } from "../lib/format.ts";
import { TRANSITIONS } from "@promo/core/winner/transitions.ts";
export function WinnersPage() {
  const campaigns = trpc.campaigns.list.useQuery(); const [cid, setCid] = useState(""); const [status, setStatus] = useState(""); const [kind, setKind] = useState("winner");
  const list = trpc.winners.list.useQuery({ campaignId: cid || undefined, status: status || undefined, kind: kind === "all" ? null : kind });
  return <>
    <PageHead title="Winners & claims" sub="Each winner moves through contact, verification, acceptance and collection. Publication is a separate, revocable step." actions={<><Select value={cid} onChange={(e) => setCid(e.target.value)}><option value="">All campaigns</option>{campaigns.data?.map((c) => <option key={c.id} value={c.id}>{c.code}</option>)}</Select><Select value={kind} onChange={(e) => setKind(e.target.value)}><option value="winner">Winners</option><option value="alternate">Alternates</option><option value="all">Both</option></Select><Select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Any status</option>{Object.keys(TRANSITIONS).map((s) => <option key={s} value={s}>{titleCase(s)}</option>)}</Select></>} />
    <Card flush>{list.isLoading ? <Loading /> : list.error ? <ErrorBox error={list.error} /> : <Table rows={list.data ?? []} keyOf={(w) => w.id} onRow={(w) => navigate(`/winners/${w.id}`)} cols={[{ h: "Period", c: (w) => w.periodCode }, { h: "#", c: (w) => `${w.kind === "alternate" ? "alt " : ""}${w.position}` }, { h: "Prize", c: (w) => w.prizeLabel }, { h: "Participant", c: (w) => w.participant ? `${w.participant.name} · ${w.participant.phone}` : "–" }, { h: "Status", c: (w) => <Badge status={w.status} /> }, { h: "Published", c: (w) => w.publication === "published" ? <Badge tone="primary">published</Badge> : w.publication === "withdrawn" ? <Badge tone="warning">withdrawn</Badge> : "" }, { h: "Claim by", c: (w) => fmtDate(w.claimExpiresAt) }, { h: "Contact attempts", c: (w) => w.contactAttempts, num: true }]} empty="No winners for this filter." />}</Card>
  </>;
}
export function WinnerDetailPage({ id }: { id: string }) {
  const q = trpc.winners.get.useQuery({ winnerId: id }); const can = useCan(); const toast = useToast(); const utils = trpc.useUtils(); const refresh = () => utils.winners.get.invalidate({ winnerId: id });
  const notify = trpc.winners.notify.useMutation({ onSuccess: refresh }); const transition = trpc.winners.transition.useMutation({ onSuccess: refresh }); const reassign = trpc.winners.reassignCollection.useMutation({ onSuccess: refresh }); const publish = trpc.winners.publish.useMutation({ onSuccess: refresh }); const unpublish = trpc.winners.unpublish.useMutation({ onSuccess: refresh });
  const [dialog, setDialog] = useState<null | { kind: "transition"; to: string } | { kind: "notify" } | { kind: "reassign" } | { kind: "unpublish" }>(null); const [claimRef, setClaimRef] = useState<string | null>(null);
  const draw = trpc.draws.get.useQuery({ drawId: q.data?.winner.drawId ?? "" }, { enabled: !!q.data }); const outlets = trpc.campaigns.outlets.useQuery({ campaignId: q.data?.winner.campaignId ?? "" }, { enabled: !!q.data });
  if (q.isLoading) return <Loading />; if (q.error) return <ErrorBox error={q.error} />; const d = q.data!; const w = d.winner; const p = d.participant; const moves = TRANSITIONS[w.status] ?? []; const manage = can("winner.manage");
  const collectionPoints = (outlets.data ?? []).filter((o) => o.membership.collectionPoint || o.collectionPoint);
  return <>
    <PageHead title={<>{w.kind === "alternate" ? "Alternate" : "Winner"} #{w.position} · {w.prizeLabel} <Badge status={w.status} /></>} sub={<>Draw <Link to={`/draws/${w.drawId}`}>{draw.data?.period?.code ?? w.drawId}</Link> · entry <Link to={`/entries/${w.entryId}`}>{w.entryId}</Link> · <Link to="/winners">All winners</Link></>} actions={<>
      {manage && w.kind === "winner" && ["selected", "unreachable"].includes(w.status) && <Button variant="primary" onClick={() => setDialog({ kind: "notify" })}>Send winner message</Button>}
      {manage && moves.map((to) => <Button key={to} variant={to === "collected" ? "primary" : ["replaced", "ineligible", "declined", "expired"].includes(to) ? "danger" : undefined} onClick={() => setDialog({ kind: "transition", to })}>{titleCase(to)}</Button>)}
      {manage && ["accepted", "verified", "collected"].includes(w.status) && <Button onClick={() => setDialog({ kind: "reassign" })}>Collection outlet</Button>}
      {can("winner.publish") && w.publication !== "published" && ["verified", "accepted", "collected"].includes(w.status) && <Button onClick={async () => { try { await publish.mutateAsync({ winnerId: id }); toast.push("Published (masked name only)", "success"); } catch (e) { toast.push(errorMessage(e), "error"); } }}>Publish</Button>}
      {can("winner.publish") && w.publication === "published" && <Button onClick={() => setDialog({ kind: "unpublish" })}>Withdraw publication</Button>}
    </>} />
    {claimRef && <Callout tone="success">Claim reference sent to the winner: <span className="mono strong">{claimRef}</span>. It is stored hashed; note it now if you need it for the collection point.</Callout>}
    <div className="tt-grid c2" style={{ marginTop: 16 }}>
      <Card title="Claim"><KV rows={[["Participant", p ? <Link to={`/participants/${p.id}`}>{p.firstName} {p.surname} · {p.phone} · {p.identityMask ?? "no identity"}</Link> : "–"], ["Identity verified", p?.identityVerifiedAt ? fmtDate(p.identityVerifiedAt) : <Badge tone="warning">not yet</Badge>], ["Public display name", w.displayName ?? "–"], ["Publication", titleCase(w.publication)], ["Claim deadline", fmtDate(w.claimExpiresAt)], ["Contact attempts", w.contactAttempts], ["Collection outlet", d.collectionOutlet ? `${d.collectionOutlet.retailer} — ${d.collectionOutlet.branch}, ${d.collectionOutlet.town}` : "not set"], ["Verified", w.verifiedAt ? `${fmtDate(w.verifiedAt)} by ${w.verifiedBy}` : "–"], ["Accepted", fmtDate(w.acceptedAt)], ["Collected", w.fulfilledAt ? `${fmtDate(w.fulfilledAt)} by ${w.fulfilledBy} · ref ${w.fulfilmentRef}` : "–"], ["Replaces / replaced by", `${w.replacesId ?? "–"} / ${w.replacedById ?? "–"}`]]} /></Card>
      <Card title="Messages"><Table rows={d.messages} keyOf={(m) => m.id} cols={[{ h: "Purpose", c: (m) => titleCase(m.purpose) }, { h: "Status", c: (m) => <Badge status={m.status} /> }, { h: "Attempts", c: (m) => m.attempts, num: true }, { h: "Error", c: (m) => m.lastError ?? "" }, { h: "Sent", c: (m) => fmtDate(m.sentAt) }, { h: "Delivered / read", c: (m) => `${fmtDate(m.deliveredAt)} / ${fmtDate(m.readAt)}` }]} empty="No messages yet." /></Card>
      <Card title="History"><Table rows={d.events} keyOf={(e) => e.id} cols={[{ h: "When", c: (e) => fmtDate(e.createdAt) }, { h: "From", c: (e) => <Badge status={e.fromStatus ?? undefined}>{titleCase(e.fromStatus ?? "–")}</Badge> }, { h: "To", c: (e) => <Badge status={e.toStatus} /> }, { h: "Actor", c: (e) => e.actorId }, { h: "Reason / note", c: (e) => [e.reason, e.note].filter(Boolean).join(" · ") }]} /></Card>
    </div>
    {dialog?.kind === "notify" && <ActionDialog title="Send the winner message" description="Queues the approved winner message with a fresh claim reference. Outside the 24-hour service window the real WhatsApp transport needs an approved template." confirmLabel="Send" onConfirm={async () => { const r = await notify.mutateAsync({ winnerId: id }); setClaimRef(r.claimRef); }} onClose={() => setDialog(null)} />}
    {dialog?.kind === "transition" && <ActionDialog title={`Mark ${titleCase(dialog.to)}`} danger={["replaced", "ineligible", "declined", "expired"].includes(dialog.to)} description={dialog.to === "verified" ? "Confirms you checked the winner's identity against the registered identity number." : dialog.to === "accepted" ? "Sends collection instructions for the chosen outlet." : dialog.to === "collected" ? "Records fulfilment at the collection outlet with a slip or reference number." : dialog.to === "replaced" ? "Promotes the first unused alternate to this prize." : undefined} confirmLabel={titleCase(dialog.to)} fields={[...(dialog.to === "verified" ? [{ key: "evidence", label: "Evidence (what you checked)", required: true }] : []), ...(dialog.to === "accepted" ? [{ key: "collectionOutletId", label: "Collection outlet", type: "select" as const, required: true, options: collectionPoints.map((o) => ({ value: o.id, label: `${o.retailer} — ${o.branch}, ${o.town}` })) }] : []), ...(dialog.to === "collected" ? [{ key: "fulfilmentRef", label: "Fulfilment reference", required: true }] : []), ...(["replaced", "ineligible", "declined", "expired", "unreachable", "disputed"].includes(dialog.to) ? [{ key: "reason", label: "Reason", required: true }] : []), { key: "note", label: "Note", type: "textarea" as const }]} onConfirm={async (v) => { const r = await transition.mutateAsync({ winnerId: id, status: dialog.to, evidence: v.evidence || undefined, collectionOutletId: v.collectionOutletId || undefined, fulfilmentRef: v.fulfilmentRef || undefined, reason: v.reason || undefined, note: v.note || undefined, expectedVersion: w.version }); toast.push(r.replacement ? `Replaced; ${r.replacement.displayName ?? "alternate"} promoted` : "Updated", "success"); }} onClose={() => setDialog(null)} />}
    {dialog?.kind === "reassign" && <ActionDialog title="Change collection outlet" fields={[{ key: "collectionOutletId", label: "Collection outlet", type: "select", required: true, options: collectionPoints.map((o) => ({ value: o.id, label: `${o.retailer} — ${o.branch}, ${o.town}` })) }, { key: "reason", label: "Reason" }]} onConfirm={async (v) => { await reassign.mutateAsync({ winnerId: id, collectionOutletId: v.collectionOutletId, reason: v.reason || undefined }); toast.push("Collection outlet updated; instructions re-sent", "success"); }} onClose={() => setDialog(null)} />}
    {dialog?.kind === "unpublish" && <ActionDialog title="Withdraw publication" fields={[{ key: "reason", label: "Reason", required: true }]} onConfirm={async (v) => { await unpublish.mutateAsync({ winnerId: id, reason: v.reason }); toast.push("Publication withdrawn", "success"); }} onClose={() => setDialog(null)} />}
  </>;
}
