import { z } from "zod";
import { router, guard } from "../trpc.ts";
import { validateActivation, DECISION_IDS, conflict } from "@promo/core";
const any = z.record(z.string(), z.unknown());
const campaignId = z.object({ campaignId: z.string() });
export const campaignsRouter = router({
  list: guard("campaign.read").query(async ({ ctx }) => { const rows = await ctx.app.campaigns.list(); return Promise.all(rows.map(async (c) => { const v = await ctx.app.campaigns.activeVersion(c.id); const d = await ctx.app.campaigns.listDecisions(c.id); return { ...c, activeVersionNo: v?.versionNo ?? null, openDecisions: d.filter((x) => x.blocksActivation && !["approved", "not_required"].includes(x.status)).length, controls: await ctx.app.campaigns.controls(c.id) }; })); }),
  get: guard("campaign.read").input(campaignId).query(async ({ ctx, input }) => { const c = await ctx.app.campaigns.get(input.campaignId); if (!c) throw conflict("campaign not found"); const v = await ctx.app.campaigns.activeVersion(c.id); return { campaign: c, activeVersion: v, versions: await ctx.app.campaigns.versions(c.id), periods: await ctx.app.campaigns.periods(c.id), decisions: await ctx.app.campaigns.listDecisions(c.id), controls: await ctx.app.campaigns.controls(c.id), outletCount: (await ctx.app.campaigns.campaignOutlets(c.id)).length }; }),
  create: guard("campaign.write").input(z.object({ code: z.string(), name: z.string(), description: z.string().max(2000).optional(), startsAt: z.string(), endsAt: z.string(), timezone: z.string().optional(), rules: any.optional(), content: any.optional(), flags: any.optional(), prizePlan: any.optional() })).mutation(({ ctx, input }) => ctx.app.campaigns.create(input, ctx.user.id)),
  update: guard("campaign.write").input(campaignId.extend({ name: z.string().optional(), description: z.string().max(2000).optional(), startsAt: z.string().optional(), endsAt: z.string().optional(), timezone: z.string().optional() })).mutation(({ ctx, input }) => ctx.app.campaigns.update(input.campaignId, input, ctx.user.id)),
  setStatus: guard("campaign.activate").input(campaignId.extend({ status: z.enum(["active", "paused", "closed", "archived"]), reason: z.string().max(300).optional() })).mutation(async ({ ctx, input }) => {
    if (input.status === "active" && ctx.app.environment === "production") { const v = await validateActivation({ cfg: ctx.app.cfg, environment: ctx.app.environment, campaignId: input.campaignId, campaigns: ctx.app.campaigns, auth: ctx.app.auth, extractor: ctx.app.extractor, transport: ctx.app.transport, crm: ctx.app.crm }); if (!v.ok) throw conflict("production activation blocked", { failures: v.failures.filter((f) => f.blocking) }); }
    return ctx.app.campaigns.setStatus(input.campaignId, input.status, ctx.user.id, input.reason ?? null);
  }),
  setControls: guard("campaign.write").input(campaignId.extend({ pauseIntake: z.boolean().optional(), pauseAutoQualify: z.boolean().optional(), pauseOutbound: z.boolean().optional(), pauseDraws: z.boolean().optional() })).mutation(({ ctx, input }) => { const { campaignId: id, ...patch } = input; return ctx.app.campaigns.setControls(id, patch, ctx.user.id); }),
  clone: guard("campaign.write").input(campaignId.extend({ code: z.string(), name: z.string().optional() })).mutation(({ ctx, input }) => ctx.app.campaigns.clone(input.campaignId, input, ctx.user.id)),
  activation: guard("campaign.read").input(campaignId).query(({ ctx, input }) => validateActivation({ cfg: ctx.app.cfg, environment: ctx.app.environment, campaignId: input.campaignId, campaigns: ctx.app.campaigns, auth: ctx.app.auth, extractor: ctx.app.extractor, transport: ctx.app.transport, crm: ctx.app.crm })),
  versions: guard("campaign.read").input(campaignId).query(({ ctx, input }) => ctx.app.campaigns.versions(input.campaignId)),
  createVersion: guard("campaign.write").input(campaignId.extend({ fromActive: z.boolean().optional(), rules: any.optional(), content: any.optional(), flags: any.optional(), prizePlan: any.optional() })).mutation(({ ctx, input }) => ctx.app.campaigns.createVersion(input.campaignId, input, ctx.user.id)),
  updateVersion: guard("campaign.write").input(z.object({ versionId: z.string(), rules: any.optional(), content: any.optional(), flags: any.optional(), prizePlan: any.optional() })).mutation(({ ctx, input }) => ctx.app.campaigns.updateDraftVersion(input.versionId, input, ctx.user.id)),
  activateVersion: guard("campaign.write").input(campaignId.extend({ versionId: z.string() })).mutation(({ ctx, input }) => ctx.app.campaigns.activateVersion(input.campaignId, input.versionId, ctx.user.id)),
  periods: guard("campaign.read").input(campaignId).query(({ ctx, input }) => ctx.app.campaigns.periods(input.campaignId)),
  upsertPeriod: guard("campaign.write").input(campaignId.extend({ code: z.string(), label: z.string().optional(), startsAt: z.string(), endsAt: z.string(), drawAt: z.string().nullable().optional(), prizePlan: any.nullable().optional(), status: z.string().optional() })).mutation(({ ctx, input }) => ctx.app.campaigns.upsertPeriod(input.campaignId, input, ctx.user.id)),
  decisions: guard("campaign.read").input(campaignId).query(({ ctx, input }) => ctx.app.campaigns.listDecisions(input.campaignId)),
  upsertDecision: guard("campaign.write").input(campaignId.extend({ decisionId: z.string(), question: z.string().optional(), testValue: z.string().nullable().optional(), approvedValue: z.string().nullable().optional(), status: z.string().optional(), owner: z.string().nullable().optional(), evidence: z.string().nullable().optional(), blocksActivation: z.boolean().optional() })).mutation(({ ctx, input }) => ctx.app.campaigns.upsertDecision(input.campaignId, input, ctx.user.id)),
  decisionIds: guard("campaign.read").query(() => DECISION_IDS),
  outlets: guard("campaign.read").input(campaignId).query(({ ctx, input }) => ctx.app.campaigns.campaignOutlets(input.campaignId)),
  setOutlets: guard("campaign.write").input(campaignId.extend({ members: z.array(z.object({ outletId: z.string(), collectionPoint: z.boolean().optional(), activeFrom: z.string().nullable().optional(), activeTo: z.string().nullable().optional() })) })).mutation(({ ctx, input }) => ctx.app.campaigns.setCampaignOutlets(input.campaignId, input.members, ctx.user.id)),
  importOutlets: guard("campaign.write").input(z.object({ campaignId: z.string().nullable(), csv: z.string().max(2_000_000), dryRun: z.boolean().default(true) })).mutation(({ ctx, input }) => ctx.app.campaigns.importOutletsCsv(input.campaignId, input.csv, { dryRun: input.dryRun, actorId: ctx.user.id })),
});
export const masterDataRouter = router({
  outlets: guard("campaign.read").query(({ ctx }) => ctx.app.campaigns.outlets()),
  upsertOutlet: guard("masterdata.write").input(z.object({ code: z.string(), retailer: z.string(), branch: z.string(), town: z.string(), region: z.string().optional(), aliases: z.array(z.string()).optional(), collectionPoint: z.boolean().optional(), active: z.boolean().optional() })).mutation(({ ctx, input }) => ctx.app.campaigns.upsertOutlet(input, ctx.user.id)),
  products: guard("campaign.read").query(({ ctx }) => ctx.app.campaigns.products()),
  upsertProduct: guard("masterdata.write").input(z.object({ sku: z.string(), brand: z.string().optional(), name: z.string(), packGrams: z.number().int().positive(), aliases: z.array(z.string()).optional(), active: z.boolean().optional() })).mutation(({ ctx, input }) => ctx.app.campaigns.upsertProduct(input, ctx.user.id)),
});
