import { z } from "zod";
import { router, guard } from "../trpc.ts";
import { notFound } from "@promo/core";
const view = <T extends { seedHex: string }>(d: T): Omit<T, "seedHex"> => { const { seedHex: _s, ...rest } = d; return rest; };
export const drawsRouter = router({
  list: guard("draw.read").input(z.object({ campaignId: z.string() })).query(async ({ ctx, input }) => (await ctx.app.draws.list(input.campaignId)).map((r) => ({ ...view(r.d), periodCode: r.periodCode, periodLabel: r.periodLabel }))),
  barrier: guard("draw.read").input(z.object({ campaignId: z.string(), periodId: z.string() })).query(async ({ ctx, input }) => { const b = await ctx.app.draws.barrier(input.campaignId, input.periodId); return { ok: b.ok, blockers: b.blockers, eligible: b.eligible.length, distinctParticipants: b.distinctParticipants, exclusions: b.exclusions.length, plan: b.plan, period: b.period }; }),
  freeze: guard("draw.execute").input(z.object({ campaignId: z.string(), periodId: z.string(), override: z.object({ allow: z.array(z.string()), reason: z.string().min(3).max(300) }).nullable().optional() })).mutation(async ({ ctx, input }) => view(await ctx.app.draws.freeze({ campaignId: input.campaignId, periodId: input.periodId, actorId: ctx.user.id, override: input.override ?? null }))),
  get: guard("draw.read").input(z.object({ drawId: z.string() })).query(async ({ ctx, input }) => { const d = await ctx.app.draws.get(input.drawId); if (!d) throw notFound("draw"); const period = await ctx.app.campaigns.period(d.periodId); return { draw: view(d), period, integrity: await ctx.app.draws.verifyStored(d), candidates: await ctx.app.draws.candidateCount(d.id), attempts: await ctx.app.draws.attempts(d.id), winners: (await ctx.app.winners.list({ drawId: d.id, kind: null })).map((w) => ({ id: w.w.id, kind: w.w.kind, position: w.w.position, status: w.w.status, publication: w.w.publication, prizeLabel: w.w.prizeLabel, displayName: w.w.displayName })) }; }),
  execute: guard("draw.execute").input(z.object({ drawId: z.string() })).mutation(async ({ ctx, input }) => view(await ctx.app.draws.execute(input.drawId, ctx.user.id))),
  approve: guard("draw.approve").input(z.object({ drawId: z.string(), expectedOutputHash: z.string().optional(), note: z.string().max(300).optional() })).mutation(async ({ ctx, input }) => view(await ctx.app.draws.approve(input.drawId, ctx.user.id, { expectedOutputHash: input.expectedOutputHash ?? null, note: input.note ?? null }))),
  reject: guard("draw.approve").input(z.object({ drawId: z.string(), reason: z.string().min(3).max(300) })).mutation(async ({ ctx, input }) => view(await ctx.app.draws.reject(input.drawId, ctx.user.id, input.reason))),
  publish: guard("winner.manage").input(z.object({ drawId: z.string() })).mutation(async ({ ctx, input }) => { const d = await ctx.app.draws.publish(input.drawId, ctx.user.id); const m = await ctx.app.winners.materialise(d.id, ctx.user.id); return { draw: view(d), ...m }; }),
  voidAndRerun: guard("draw.execute").input(z.object({ drawId: z.string(), reason: z.string().min(3).max(300), approvedBy: z.string() })).mutation(async ({ ctx, input }) => view(await ctx.app.draws.voidAndRerun(input.drawId, ctx.user.id, input.reason, input.approvedBy))),
  bundle: guard("draw.bundle").input(z.object({ drawId: z.string() })).query(({ ctx, input }) => ctx.app.draws.bundle(input.drawId, ctx.user.id)),
  verify: guard("draw.read").input(z.object({ drawId: z.string() })).query(async ({ ctx, input }) => { const d = await ctx.app.draws.get(input.drawId); if (!d) throw notFound("draw"); return ctx.app.draws.verifyStored(d); }),
});
export const winnersRouter = router({
  list: guard("winner.read").input(z.object({ campaignId: z.string().optional(), drawId: z.string().optional(), status: z.string().optional(), kind: z.string().nullable().optional() })).query(async ({ ctx, input }) => (await ctx.app.winners.list({ campaignId: input.campaignId ?? null, drawId: input.drawId ?? null, status: input.status ?? null, kind: input.kind === undefined ? "winner" : input.kind })).map((r) => ({ ...r.w, claimTokenHash: undefined, periodCode: r.periodCode, participant: r.participant ? { name: `${r.participant.firstName} ${r.participant.surname}`.trim(), phone: `***${r.participant.channelUid.slice(-4)}`, location: r.participant.location, status: r.participant.status } : null }))),
  get: guard("winner.read").input(z.object({ winnerId: z.string() })).query(async ({ ctx, input }) => { const w = await ctx.app.winners.get(input.winnerId); if (!w) throw notFound("winner"); const p = await ctx.app.participants.get(w.participantId); const msgs = await ctx.app.outbox.byKeyPrefix(`winner:${w.id}:`); return { winner: { ...w, claimTokenHash: undefined }, participant: ctx.app.participants.mask(p), collectionOutlet: w.collectionOutletId ? await ctx.app.campaigns.outlet(w.collectionOutletId) : null, events: await ctx.app.winners.events(w.id), messages: msgs.map((m) => ({ id: m.id, purpose: m.purpose, status: m.status, attempts: m.attempts, errorCode: m.errorCode, lastError: m.lastError, createdAt: m.createdAt, sentAt: m.sentAt, deliveredAt: m.deliveredAt, readAt: m.readAt })), entry: await ctx.app.winners.entryOf(w) }; }),
  notify: guard("winner.manage").input(z.object({ winnerId: z.string() })).mutation(({ ctx, input }) => ctx.app.winners.notify(input.winnerId, ctx.user.id)),
  transition: guard("winner.manage").input(z.object({ winnerId: z.string(), status: z.string(), note: z.string().max(500).optional(), reason: z.string().max(300).optional(), expectedVersion: z.number().int().optional(), collectionOutletId: z.string().optional(), fulfilmentRef: z.string().max(120).optional(), evidence: z.string().max(300).optional() })).mutation(async ({ ctx, input }) => { const r = await ctx.app.winners.transition(input.winnerId, { ...input, actorId: ctx.user.id }); return { winner: { ...r.winner, claimTokenHash: undefined }, replacement: "replacement" in r && r.replacement ? { id: r.replacement.id, displayName: r.replacement.displayName } : null }; }),
  reassignCollection: guard("winner.manage").input(z.object({ winnerId: z.string(), collectionOutletId: z.string(), reason: z.string().max(300).optional() })).mutation(async ({ ctx, input }) => { const r = await ctx.app.winners.reassignCollection(input.winnerId, { actorId: ctx.user.id, collectionOutletId: input.collectionOutletId, reason: input.reason ?? null }); return { winner: { ...r.winner, claimTokenHash: undefined } }; }),
  publish: guard("winner.publish").input(z.object({ winnerId: z.string() })).mutation(async ({ ctx, input }) => ({ ...(await ctx.app.winners.publish(input.winnerId, ctx.user.id)), claimTokenHash: undefined })),
  unpublish: guard("winner.publish").input(z.object({ winnerId: z.string(), reason: z.string().min(3).max(300) })).mutation(async ({ ctx, input }) => ({ ...(await ctx.app.winners.unpublish(input.winnerId, ctx.user.id, input.reason)), claimTokenHash: undefined })),
});
