import { z } from "zod";
import { appRouter } from "./router.ts";
/** Machine-readable API contract generated from the tRPC router: procedure, type, input JSON schema, required permission (from the guard). Served at /api/contract.json and written to docs/api/contract.json. */
export function contractDocument() {
  const procedures: Array<{ path: string; type: string; input: unknown }> = [];
  const walk = (r: Record<string, unknown>, prefix: string) => { for (const [k, v] of Object.entries(r)) { const def = (v as { _def?: { procedure?: boolean; type?: string; inputs?: unknown[]; record?: Record<string, unknown> } })._def; if (!def) continue; if (def.procedure) { const input = def.inputs?.[0]; let schema: unknown = null; try { schema = input ? z.toJSONSchema(input as z.ZodType, { unrepresentable: "any" }) : null; } catch { schema = "unrepresentable"; } procedures.push({ path: prefix + k, type: def.type ?? "unknown", input: schema }); } else if (def.record) walk(def.record, prefix + k + "."); } };
  walk((appRouter as unknown as { _def: { record: Record<string, unknown> } })._def.record, "");
  return { contract: "hullets-api/1", transport: "tRPC 11 over HTTP (POST /trpc/<path> for mutations, GET for queries; batch supported)", auth: "Authorization: Bearer <session token> from auth.login / auth.verifyMfa", errors: "tRPC error envelope with data.domainCode (VALIDATION, NOT_FOUND, CONFLICT, FORBIDDEN, UNAUTHORIZED, SOD, BLOCKED, INTEGRITY, APPROVAL_REQUIRED, IDENTITY_INCOMPLETE, RATE_LIMITED); unknown input fields are stripped", rest: [{ path: "GET /webhooks/whatsapp", note: "Meta verify handshake" }, { path: "POST /webhooks/whatsapp", note: "signed provider events; durable-then-ack; 503 asks the provider to retry" }, { path: "GET /api/media/:submissionId?v=normalised", note: "bearer; submission.media permission; audited" }, { path: "GET /api/export/:scope.csv", note: "bearer; report.export; formula-safe; watermarked" }, { path: "GET /api/draws/:drawId/bundle.json", note: "bearer; draw.bundle; independent verifier input" }, { path: "GET /health/live | /health/ready", note: "liveness / readiness" }], procedures };
}
